tellraw @p {"rawtext":[{"translate":"ball.free"}]}
playsound serp.pokeball.free @s

execute @s[tag=c1,tag=!shiny] ~~~ summon serp:bulbasaur ~~~ serp:normal
execute @s[tag=c1,tag=shiny] ~~~ summon serp:bulbasaur ~~~ serp:shiny
execute @s[tag=c2,tag=!shiny] ~~~ summon serp:ivysaur ~~~ serp:normal
execute @s[tag=c2,tag=shiny] ~~~ summon serp:ivysaur ~~~ serp:shiny
execute @s[tag=c3,tag=!shiny] ~~~ summon serp:venusaur ~~~ serp:normal
execute @s[tag=c3,tag=shiny] ~~~ summon serp:venusaur ~~~ serp:shiny
execute @s[tag=c4,tag=!shiny] ~~~ summon serp:charmander ~~~ serp:normal
execute @s[tag=c4,tag=shiny] ~~~ summon serp:charmander ~~~ serp:shiny
execute @s[tag=c5,tag=!shiny] ~~~ summon serp:charmeleon ~~~ serp:normal
execute @s[tag=c5,tag=shiny] ~~~ summon serp:charmeleon ~~~ serp:shiny
execute @s[tag=c6,tag=!shiny] ~~~ summon serp:charizard ~~~ serp:normal
execute @s[tag=c6,tag=shiny] ~~~ summon serp:charizard ~~~ serp:shiny
execute @s[tag=c7,tag=!shiny] ~~~ summon serp:squirtle ~~~ serp:normal
execute @s[tag=c7,tag=shiny] ~~~ summon serp:squirtle ~~~ serp:shiny
execute @s[tag=c8,tag=!shiny] ~~~ summon serp:wartortle ~~~ serp:normal
execute @s[tag=c8,tag=shiny] ~~~ summon serp:wartortle ~~~ serp:shiny
execute @s[tag=c9,tag=!shiny] ~~~ summon serp:blastoise ~~~ serp:normal
execute @s[tag=c9,tag=shiny] ~~~ summon serp:blastoise ~~~ serp:shiny
execute @s[tag=c10,tag=!shiny] ~~~ summon serp:caterpie ~~~ serp:normal
execute @s[tag=c10,tag=shiny] ~~~ summon serp:caterpie ~~~ serp:shiny
execute @s[tag=c11,tag=!shiny] ~~~ summon serp:metapod ~~~ serp:normal
execute @s[tag=c11,tag=shiny] ~~~ summon serp:metapod ~~~ serp:shiny
execute @s[tag=c12,tag=!shiny] ~~~ summon serp:butterfree ~~~ serp:normal
execute @s[tag=c12,tag=shiny] ~~~ summon serp:butterfree ~~~ serp:shiny
execute @s[tag=c13,tag=!shiny] ~~~ summon serp:weedle ~~~ serp:normal
execute @s[tag=c13,tag=shiny] ~~~ summon serp:weedle ~~~ serp:shiny
execute @s[tag=c14,tag=!shiny] ~~~ summon serp:kakuna ~~~ serp:normal
execute @s[tag=c14,tag=shiny] ~~~ summon serp:kakuna ~~~ serp:shiny
execute @s[tag=c15,tag=!shiny] ~~~ summon serp:beedrill ~~~ serp:normal
execute @s[tag=c15,tag=shiny] ~~~ summon serp:beedrill ~~~ serp:shiny
execute @s[tag=c16,tag=!shiny] ~~~ summon serp:pidgey ~~~ serp:normal
execute @s[tag=c16,tag=shiny] ~~~ summon serp:pidgey ~~~ serp:shiny
execute @s[tag=c17,tag=!shiny] ~~~ summon serp:pidgeotto ~~~ serp:normal
execute @s[tag=c17,tag=shiny] ~~~ summon serp:pidgeotto ~~~ serp:shiny
execute @s[tag=c18,tag=!shiny] ~~~ summon serp:pidgeot ~~~ serp:normal
execute @s[tag=c18,tag=shiny] ~~~ summon serp:pidgeot ~~~ serp:shiny
execute @s[tag=c19,tag=!shiny] ~~~ summon serp:rattata ~~~ serp:normal
execute @s[tag=c19,tag=shiny] ~~~ summon serp:rattata ~~~ serp:shiny
execute @s[tag=c20,tag=!shiny] ~~~ summon serp:raticate ~~~ serp:normal
execute @s[tag=c20,tag=shiny] ~~~ summon serp:raticate ~~~ serp:shiny
execute @s[tag=c21,tag=!shiny] ~~~ summon serp:spearow ~~~ serp:normal
execute @s[tag=c21,tag=shiny] ~~~ summon serp:spearow ~~~ serp:shiny
execute @s[tag=c22,tag=!shiny] ~~~ summon serp:fearow ~~~ serp:normal
execute @s[tag=c22,tag=shiny] ~~~ summon serp:fearow ~~~ serp:shiny
execute @s[tag=c23,tag=!shiny] ~~~ summon serp:ekans ~~~ serp:normal
execute @s[tag=c23,tag=shiny] ~~~ summon serp:ekans ~~~ serp:shiny
execute @s[tag=c24,tag=!shiny] ~~~ summon serp:arbok ~~~ serp:normal
execute @s[tag=c24,tag=shiny] ~~~ summon serp:arbok ~~~ serp:shiny
execute @s[tag=c25,tag=!shiny] ~~~ summon serp:pikachu ~~~ serp:normal
execute @s[tag=c25,tag=shiny] ~~~ summon serp:pikachu ~~~ serp:shiny
execute @s[tag=c26,tag=!shiny] ~~~ summon serp:raichu ~~~ serp:normal
execute @s[tag=c26,tag=shiny] ~~~ summon serp:raichu ~~~ serp:shiny
execute @s[tag=c27,tag=!shiny] ~~~ summon serp:sandshrew ~~~ serp:normal
execute @s[tag=c27,tag=shiny] ~~~ summon serp:sandshrew ~~~ serp:shiny
execute @s[tag=c28,tag=!shiny] ~~~ summon serp:sandslash ~~~ serp:normal
execute @s[tag=c28,tag=shiny] ~~~ summon serp:sandslash ~~~ serp:shiny
execute @s[tag=c29,tag=!shiny] ~~~ summon serp:nidoranh ~~~ serp:normal
execute @s[tag=c29,tag=shiny] ~~~ summon serp:nidoranh ~~~ serp:shiny
execute @s[tag=c30,tag=!shiny] ~~~ summon serp:nidorina ~~~ serp:normal
execute @s[tag=c30,tag=shiny] ~~~ summon serp:nidorina ~~~ serp:shiny
execute @s[tag=c31,tag=!shiny] ~~~ summon serp:nidoqueen ~~~ serp:normal
execute @s[tag=c31,tag=shiny] ~~~ summon serp:nidoqueen ~~~ serp:shiny
execute @s[tag=c32,tag=!shiny] ~~~ summon serp:nidoranm ~~~ serp:normal
execute @s[tag=c32,tag=shiny] ~~~ summon serp:nidoranm ~~~ serp:shiny
execute @s[tag=c33,tag=!shiny] ~~~ summon serp:nidorino ~~~ serp:normal
execute @s[tag=c33,tag=shiny] ~~~ summon serp:nidorino ~~~ serp:shiny
execute @s[tag=c34,tag=!shiny] ~~~ summon serp:nidoking ~~~ serp:normal
execute @s[tag=c34,tag=shiny] ~~~ summon serp:nidoking ~~~ serp:shiny
execute @s[tag=c35,tag=!shiny] ~~~ summon serp:clefairy ~~~ serp:normal
execute @s[tag=c35,tag=shiny] ~~~ summon serp:clefairy ~~~ serp:shiny
execute @s[tag=c36,tag=!shiny] ~~~ summon serp:clefable ~~~ serp:normal
execute @s[tag=c36,tag=shiny] ~~~ summon serp:clefable ~~~ serp:shiny
execute @s[tag=c37,tag=!shiny] ~~~ summon serp:vulpix ~~~ serp:normal
execute @s[tag=c37,tag=shiny] ~~~ summon serp:vulpix ~~~ serp:shiny
execute @s[tag=c38,tag=!shiny] ~~~ summon serp:ninetales ~~~ serp:normal
execute @s[tag=c38,tag=shiny] ~~~ summon serp:ninetales ~~~ serp:shiny
execute @s[tag=c39,tag=!shiny] ~~~ summon serp:jigglypuff ~~~ serp:normal
execute @s[tag=c39,tag=shiny] ~~~ summon serp:jigglypuff ~~~ serp:shiny
execute @s[tag=c40,tag=!shiny] ~~~ summon serp:wigglytuff ~~~ serp:normal
execute @s[tag=c40,tag=shiny] ~~~ summon serp:wigglytuff ~~~ serp:shiny
execute @s[tag=c41,tag=!shiny] ~~~ summon serp:zubat ~~~ serp:normal
execute @s[tag=c41,tag=shiny] ~~~ summon serp:zubat ~~~ serp:shiny
execute @s[tag=c42,tag=!shiny] ~~~ summon serp:golbat ~~~ serp:normal
execute @s[tag=c42,tag=shiny] ~~~ summon serp:golbat ~~~ serp:shiny
execute @s[tag=c43,tag=!shiny] ~~~ summon serp:oddish ~~~ serp:normal
execute @s[tag=c43,tag=shiny] ~~~ summon serp:oddish ~~~ serp:shiny
execute @s[tag=c44,tag=!shiny] ~~~ summon serp:gloom ~~~ serp:normal
execute @s[tag=c44,tag=shiny] ~~~ summon serp:gloom ~~~ serp:shiny
execute @s[tag=c45,tag=!shiny] ~~~ summon serp:vileplume ~~~ serp:normal
execute @s[tag=c45,tag=shiny] ~~~ summon serp:vileplume ~~~ serp:shiny
execute @s[tag=c46,tag=!shiny] ~~~ summon serp:paras ~~~ serp:normal
execute @s[tag=c46,tag=shiny] ~~~ summon serp:paras ~~~ serp:shiny
execute @s[tag=c47,tag=!shiny] ~~~ summon serp:parasect ~~~ serp:normal
execute @s[tag=c47,tag=shiny] ~~~ summon serp:parasect ~~~ serp:shiny
execute @s[tag=c48,tag=!shiny] ~~~ summon serp:venonat ~~~ serp:normal
execute @s[tag=c48,tag=shiny] ~~~ summon serp:venonat ~~~ serp:shiny
execute @s[tag=c49,tag=!shiny] ~~~ summon serp:venomoth ~~~ serp:normal
execute @s[tag=c49,tag=shiny] ~~~ summon serp:venomoth ~~~ serp:shiny
execute @s[tag=c50,tag=!shiny] ~~~ summon serp:diglett ~~~ serp:normal
execute @s[tag=c50,tag=shiny] ~~~ summon serp:diglett ~~~ serp:shiny
execute @s[tag=c51,tag=!shiny] ~~~ summon serp:dugtrio ~~~ serp:normal
execute @s[tag=c51,tag=shiny] ~~~ summon serp:dugtrio ~~~ serp:shiny
execute @s[tag=c52,tag=!shiny] ~~~ summon serp:meowth ~~~ serp:normal
execute @s[tag=c52,tag=shiny] ~~~ summon serp:meowth ~~~ serp:shiny
execute @s[tag=c53,tag=!shiny] ~~~ summon serp:persian ~~~ serp:normal
execute @s[tag=c53,tag=shiny] ~~~ summon serp:persian ~~~ serp:shiny
execute @s[tag=c54,tag=!shiny] ~~~ summon serp:psyduck ~~~ serp:normal
execute @s[tag=c54,tag=shiny] ~~~ summon serp:psyduck ~~~ serp:shiny
execute @s[tag=c55,tag=!shiny] ~~~ summon serp:golduck ~~~ serp:normal
execute @s[tag=c55,tag=shiny] ~~~ summon serp:golduck ~~~ serp:shiny
execute @s[tag=c56,tag=!shiny] ~~~ summon serp:mankey ~~~ serp:normal
execute @s[tag=c56,tag=shiny] ~~~ summon serp:mankey ~~~ serp:shiny
execute @s[tag=c57,tag=!shiny] ~~~ summon serp:primeape ~~~ serp:normal
execute @s[tag=c57,tag=shiny] ~~~ summon serp:primeape ~~~ serp:shiny
execute @s[tag=c58,tag=!shiny] ~~~ summon serp:growlithe ~~~ serp:normal
execute @s[tag=c58,tag=shiny] ~~~ summon serp:growlithe ~~~ serp:shiny
execute @s[tag=c59,tag=!shiny] ~~~ summon serp:arcanine ~~~ serp:normal
execute @s[tag=c59,tag=shiny] ~~~ summon serp:arcanine ~~~ serp:shiny
execute @s[tag=c60,tag=!shiny] ~~~ summon serp:poliwag ~~~ serp:normal
execute @s[tag=c60,tag=shiny] ~~~ summon serp:poliwag ~~~ serp:shiny
execute @s[tag=c61,tag=!shiny] ~~~ summon serp:poliwhirl ~~~ serp:normal
execute @s[tag=c61,tag=shiny] ~~~ summon serp:poliwhirl ~~~ serp:shiny
execute @s[tag=c62,tag=!shiny] ~~~ summon serp:poliwrath ~~~ serp:normal
execute @s[tag=c62,tag=shiny] ~~~ summon serp:poliwrath ~~~ serp:shiny
execute @s[tag=c63,tag=!shiny] ~~~ summon serp:abra ~~~ serp:normal
execute @s[tag=c63,tag=shiny] ~~~ summon serp:abra ~~~ serp:shiny
execute @s[tag=c64,tag=!shiny] ~~~ summon serp:kadabra ~~~ serp:normal
execute @s[tag=c64,tag=shiny] ~~~ summon serp:kadabra ~~~ serp:shiny
execute @s[tag=c65,tag=!shiny] ~~~ summon serp:alakazam ~~~ serp:normal
execute @s[tag=c65,tag=shiny] ~~~ summon serp:alakazam ~~~ serp:shiny
execute @s[tag=c66,tag=!shiny] ~~~ summon serp:machop ~~~ serp:normal
execute @s[tag=c66,tag=shiny] ~~~ summon serp:machop ~~~ serp:shiny
execute @s[tag=c67,tag=!shiny] ~~~ summon serp:machoke ~~~ serp:normal
execute @s[tag=c67,tag=shiny] ~~~ summon serp:machoke ~~~ serp:shiny
execute @s[tag=c68,tag=!shiny] ~~~ summon serp:machamp ~~~ serp:normal
execute @s[tag=c68,tag=shiny] ~~~ summon serp:machamp ~~~ serp:shiny
execute @s[tag=c69,tag=!shiny] ~~~ summon serp:bellsprout ~~~ serp:normal
execute @s[tag=c69,tag=shiny] ~~~ summon serp:bellsprout ~~~ serp:shiny
execute @s[tag=c70,tag=!shiny] ~~~ summon serp:weepinbell ~~~ serp:normal
execute @s[tag=c70,tag=shiny] ~~~ summon serp:weepinbell ~~~ serp:shiny
execute @s[tag=c71,tag=!shiny] ~~~ summon serp:victreebel ~~~ serp:normal
execute @s[tag=c71,tag=shiny] ~~~ summon serp:victreebel ~~~ serp:shiny
execute @s[tag=c72,tag=!shiny] ~~~ summon serp:tentacool ~~~ serp:normal
execute @s[tag=c72,tag=shiny] ~~~ summon serp:tentacool ~~~ serp:shiny
execute @s[tag=c73,tag=!shiny] ~~~ summon serp:tentacruel ~~~ serp:normal
execute @s[tag=c73,tag=shiny] ~~~ summon serp:tentacruel ~~~ serp:shiny
execute @s[tag=c74,tag=!shiny] ~~~ summon serp:geodude ~~~ serp:normal
execute @s[tag=c74,tag=shiny] ~~~ summon serp:geodude ~~~ serp:shiny
execute @s[tag=c75,tag=!shiny] ~~~ summon serp:graveler ~~~ serp:normal
execute @s[tag=c75,tag=shiny] ~~~ summon serp:graveler ~~~ serp:shiny
execute @s[tag=c76,tag=!shiny] ~~~ summon serp:golem ~~~ serp:normal
execute @s[tag=c76,tag=shiny] ~~~ summon serp:golem ~~~ serp:shiny
execute @s[tag=c77,tag=!shiny] ~~~ summon serp:ponyta ~~~ serp:normal
execute @s[tag=c77,tag=shiny] ~~~ summon serp:ponyta ~~~ serp:shiny
execute @s[tag=c78,tag=!shiny] ~~~ summon serp:rapidash ~~~ serp:normal
execute @s[tag=c78,tag=shiny] ~~~ summon serp:rapidash ~~~ serp:shiny
execute @s[tag=c79,tag=!shiny] ~~~ summon serp:slowpoke ~~~ serp:normal
execute @s[tag=c79,tag=shiny] ~~~ summon serp:slowpoke ~~~ serp:shiny
execute @s[tag=c80,tag=!shiny] ~~~ summon serp:slowbro ~~~ serp:normal
execute @s[tag=c80,tag=shiny] ~~~ summon serp:slowbro ~~~ serp:shiny
execute @s[tag=c81,tag=!shiny] ~~~ summon serp:magnemite ~~~ serp:normal
execute @s[tag=c81,tag=shiny] ~~~ summon serp:magnemite ~~~ serp:shiny
execute @s[tag=c82,tag=!shiny] ~~~ summon serp:magneton ~~~ serp:normal
execute @s[tag=c82,tag=shiny] ~~~ summon serp:magneton ~~~ serp:shiny
execute @s[tag=c83,tag=!shiny] ~~~ summon serp:farfetchd ~~~ serp:normal
execute @s[tag=c83,tag=shiny] ~~~ summon serp:farfetchd ~~~ serp:shiny
execute @s[tag=c84,tag=!shiny] ~~~ summon serp:doduo ~~~ serp:normal
execute @s[tag=c84,tag=shiny] ~~~ summon serp:doduo ~~~ serp:shiny
execute @s[tag=c85,tag=!shiny] ~~~ summon serp:dodrio ~~~ serp:normal
execute @s[tag=c85,tag=shiny] ~~~ summon serp:dodrio ~~~ serp:shiny
execute @s[tag=c86,tag=!shiny] ~~~ summon serp:seel ~~~ serp:normal
execute @s[tag=c86,tag=shiny] ~~~ summon serp:seel ~~~ serp:shiny
execute @s[tag=c87,tag=!shiny] ~~~ summon serp:dewgong ~~~ serp:normal
execute @s[tag=c87,tag=shiny] ~~~ summon serp:dewgong ~~~ serp:shiny
execute @s[tag=c88,tag=!shiny] ~~~ summon serp:grimer ~~~ serp:normal
execute @s[tag=c88,tag=shiny] ~~~ summon serp:grimer ~~~ serp:shiny
execute @s[tag=c89,tag=!shiny] ~~~ summon serp:muk ~~~ serp:normal
execute @s[tag=c89,tag=shiny] ~~~ summon serp:muk ~~~ serp:shiny
execute @s[tag=c90,tag=!shiny] ~~~ summon serp:shellder ~~~ serp:normal
execute @s[tag=c90,tag=shiny] ~~~ summon serp:shellder ~~~ serp:shiny
execute @s[tag=c91,tag=!shiny] ~~~ summon serp:cloyster ~~~ serp:normal
execute @s[tag=c91,tag=shiny] ~~~ summon serp:cloyster ~~~ serp:shiny
execute @s[tag=c92,tag=!shiny] ~~~ summon serp:gastly ~~~ serp:normal
execute @s[tag=c92,tag=shiny] ~~~ summon serp:gastly ~~~ serp:shiny
execute @s[tag=c93,tag=!shiny] ~~~ summon serp:haunter ~~~ serp:normal
execute @s[tag=c93,tag=shiny] ~~~ summon serp:haunter ~~~ serp:shiny
execute @s[tag=c94,tag=!shiny] ~~~ summon serp:gengar ~~~ serp:normal
execute @s[tag=c94,tag=shiny] ~~~ summon serp:gengar ~~~ serp:shiny
execute @s[tag=c95,tag=!shiny] ~~~ summon serp:onix ~~~ serp:normal
execute @s[tag=c95,tag=shiny] ~~~ summon serp:onix ~~~ serp:shiny
execute @s[tag=c96,tag=!shiny] ~~~ summon serp:drowzee ~~~ serp:normal
execute @s[tag=c96,tag=shiny] ~~~ summon serp:drowzee ~~~ serp:shiny
execute @s[tag=c97,tag=!shiny] ~~~ summon serp:hypno ~~~ serp:normal
execute @s[tag=c97,tag=shiny] ~~~ summon serp:hypno ~~~ serp:shiny
execute @s[tag=c98,tag=!shiny] ~~~ summon serp:krabby ~~~ serp:normal
execute @s[tag=c98,tag=shiny] ~~~ summon serp:krabby ~~~ serp:shiny
execute @s[tag=c99,tag=!shiny] ~~~ summon serp:kingler ~~~ serp:normal
execute @s[tag=c99,tag=shiny] ~~~ summon serp:kingler ~~~ serp:shiny
execute @s[tag=c100,tag=!shiny] ~~~ summon serp:voltorb ~~~ serp:normal
execute @s[tag=c100,tag=shiny] ~~~ summon serp:voltorb ~~~ serp:shiny
execute @s[tag=c101,tag=!shiny] ~~~ summon serp:electrode ~~~ serp:normal
execute @s[tag=c101,tag=shiny] ~~~ summon serp:electrode ~~~ serp:shiny
execute @s[tag=c102,tag=!shiny] ~~~ summon serp:exeggcute ~~~ serp:normal
execute @s[tag=c102,tag=shiny] ~~~ summon serp:exeggcute ~~~ serp:shiny
execute @s[tag=c103,tag=!shiny] ~~~ summon serp:exeggutor ~~~ serp:normal
execute @s[tag=c103,tag=shiny] ~~~ summon serp:exeggutor ~~~ serp:shiny
execute @s[tag=c104,tag=!shiny] ~~~ summon serp:cubone ~~~ serp:normal
execute @s[tag=c104,tag=shiny] ~~~ summon serp:cubone ~~~ serp:shiny
execute @s[tag=c105,tag=!shiny] ~~~ summon serp:marowak ~~~ serp:normal
execute @s[tag=c105,tag=shiny] ~~~ summon serp:marowak ~~~ serp:shiny
execute @s[tag=c106,tag=!shiny] ~~~ summon serp:hitmonlee ~~~ serp:normal
execute @s[tag=c106,tag=shiny] ~~~ summon serp:hitmonlee ~~~ serp:shiny
execute @s[tag=c107,tag=!shiny] ~~~ summon serp:hitmonchan ~~~ serp:normal
execute @s[tag=c107,tag=shiny] ~~~ summon serp:hitmonchan ~~~ serp:shiny
execute @s[tag=c108,tag=!shiny] ~~~ summon serp:lickitung ~~~ serp:normal
execute @s[tag=c108,tag=shiny] ~~~ summon serp:lickitung ~~~ serp:shiny
execute @s[tag=c109,tag=!shiny] ~~~ summon serp:koffing ~~~ serp:normal
execute @s[tag=c109,tag=shiny] ~~~ summon serp:koffing ~~~ serp:shiny
execute @s[tag=c110,tag=!shiny] ~~~ summon serp:weezing ~~~ serp:normal
execute @s[tag=c110,tag=shiny] ~~~ summon serp:weezing ~~~ serp:shiny
execute @s[tag=c111,tag=!shiny] ~~~ summon serp:rhyhorn ~~~ serp:normal
execute @s[tag=c111,tag=shiny] ~~~ summon serp:rhyhorn ~~~ serp:shiny
execute @s[tag=c112,tag=!shiny] ~~~ summon serp:rhydon ~~~ serp:normal
execute @s[tag=c112,tag=shiny] ~~~ summon serp:rhydon ~~~ serp:shiny
execute @s[tag=c113,tag=!shiny] ~~~ summon serp:chansey ~~~ serp:normal
execute @s[tag=c113,tag=shiny] ~~~ summon serp:chansey ~~~ serp:shiny
execute @s[tag=c114,tag=!shiny] ~~~ summon serp:tangela ~~~ serp:normal
execute @s[tag=c114,tag=shiny] ~~~ summon serp:tangela ~~~ serp:shiny
execute @s[tag=c115,tag=!shiny] ~~~ summon serp:kangaskhan ~~~ serp:normal
execute @s[tag=c115,tag=shiny] ~~~ summon serp:kangaskhan ~~~ serp:shiny
execute @s[tag=c116,tag=!shiny] ~~~ summon serp:horsea ~~~ serp:normal
execute @s[tag=c116,tag=shiny] ~~~ summon serp:horsea ~~~ serp:shiny
execute @s[tag=c117,tag=!shiny] ~~~ summon serp:seadra ~~~ serp:normal
execute @s[tag=c117,tag=shiny] ~~~ summon serp:seadra ~~~ serp:shiny
execute @s[tag=c118,tag=!shiny] ~~~ summon serp:goldeen ~~~ serp:normal
execute @s[tag=c118,tag=shiny] ~~~ summon serp:goldeen ~~~ serp:shiny
execute @s[tag=c119,tag=!shiny] ~~~ summon serp:seaking ~~~ serp:normal
execute @s[tag=c119,tag=shiny] ~~~ summon serp:seaking ~~~ serp:shiny
execute @s[tag=c120,tag=!shiny] ~~~ summon serp:staryu ~~~ serp:normal
execute @s[tag=c120,tag=shiny] ~~~ summon serp:staryu ~~~ serp:shiny
execute @s[tag=c121,tag=!shiny] ~~~ summon serp:starmie ~~~ serp:normal
execute @s[tag=c121,tag=shiny] ~~~ summon serp:starmie ~~~ serp:shiny
execute @s[tag=c122,tag=!shiny] ~~~ summon serp:mrmime ~~~ serp:normal
execute @s[tag=c122,tag=shiny] ~~~ summon serp:mrmime ~~~ serp:shiny
execute @s[tag=c123,tag=!shiny] ~~~ summon serp:scyther ~~~ serp:normal
execute @s[tag=c123,tag=shiny] ~~~ summon serp:scyther ~~~ serp:shiny
execute @s[tag=c124,tag=!shiny] ~~~ summon serp:jynx ~~~ serp:normal
execute @s[tag=c124,tag=shiny] ~~~ summon serp:jynx ~~~ serp:shiny
execute @s[tag=c125,tag=!shiny] ~~~ summon serp:electabuzz ~~~ serp:normal
execute @s[tag=c125,tag=shiny] ~~~ summon serp:electabuzz ~~~ serp:shiny
execute @s[tag=c126,tag=!shiny] ~~~ summon serp:magmar ~~~ serp:normal
execute @s[tag=c126,tag=shiny] ~~~ summon serp:magmar ~~~ serp:shiny
execute @s[tag=c127,tag=!shiny] ~~~ summon serp:pinsir ~~~ serp:normal
execute @s[tag=c127,tag=shiny] ~~~ summon serp:pinsir ~~~ serp:shiny
execute @s[tag=c128,tag=!shiny] ~~~ summon serp:tauros ~~~ serp:normal
execute @s[tag=c128,tag=shiny] ~~~ summon serp:tauros ~~~ serp:shiny
execute @s[tag=c129,tag=!shiny] ~~~ summon serp:magikarp ~~~ serp:normal
execute @s[tag=c129,tag=shiny] ~~~ summon serp:magikarp ~~~ serp:shiny
execute @s[tag=c130,tag=!shiny] ~~~ summon serp:gyarados ~~~ serp:normal
execute @s[tag=c130,tag=shiny] ~~~ summon serp:gyarados ~~~ serp:shiny
execute @s[tag=c131,tag=!shiny] ~~~ summon serp:lapras ~~~ serp:normal
execute @s[tag=c131,tag=shiny] ~~~ summon serp:lapras ~~~ serp:shiny
execute @s[tag=c132,tag=!shiny] ~~~ summon serp:ditto ~~~ serp:normal
execute @s[tag=c132,tag=shiny] ~~~ summon serp:ditto ~~~ serp:shiny
execute @s[tag=c133,tag=!shiny] ~~~ summon serp:eevee ~~~ serp:normal
execute @s[tag=c133,tag=shiny] ~~~ summon serp:eevee ~~~ serp:shiny
execute @s[tag=c134,tag=!shiny] ~~~ summon serp:vaporeon ~~~ serp:normal
execute @s[tag=c134,tag=shiny] ~~~ summon serp:vaporeon ~~~ serp:shiny
execute @s[tag=c135,tag=!shiny] ~~~ summon serp:jolteon ~~~ serp:normal
execute @s[tag=c135,tag=shiny] ~~~ summon serp:jolteon ~~~ serp:shiny
execute @s[tag=c136,tag=!shiny] ~~~ summon serp:flareon ~~~ serp:normal
execute @s[tag=c136,tag=shiny] ~~~ summon serp:flareon ~~~ serp:shiny
execute @s[tag=c137,tag=!shiny] ~~~ summon serp:porygon ~~~ serp:normal
execute @s[tag=c137,tag=shiny] ~~~ summon serp:porygon ~~~ serp:shiny
execute @s[tag=c138,tag=!shiny] ~~~ summon serp:omanyte ~~~ serp:normal
execute @s[tag=c138,tag=shiny] ~~~ summon serp:omanyte ~~~ serp:shiny
execute @s[tag=c139,tag=!shiny] ~~~ summon serp:omastar ~~~ serp:normal
execute @s[tag=c139,tag=shiny] ~~~ summon serp:omastar ~~~ serp:shiny
execute @s[tag=c140,tag=!shiny] ~~~ summon serp:kabuto ~~~ serp:normal
execute @s[tag=c140,tag=shiny] ~~~ summon serp:kabuto ~~~ serp:shiny
execute @s[tag=c141,tag=!shiny] ~~~ summon serp:kabutops ~~~ serp:normal
execute @s[tag=c141,tag=shiny] ~~~ summon serp:kabutops ~~~ serp:shiny
execute @s[tag=c142,tag=!shiny] ~~~ summon serp:aerodactyl ~~~ serp:normal
execute @s[tag=c142,tag=shiny] ~~~ summon serp:aerodactyl ~~~ serp:shiny
execute @s[tag=c143,tag=!shiny] ~~~ summon serp:snorlax ~~~ serp:normal
execute @s[tag=c143,tag=shiny] ~~~ summon serp:snorlax ~~~ serp:shiny
execute @s[tag=c144,tag=!shiny] ~~~ summon serp:articuno ~~~ serp:normal
execute @s[tag=c144,tag=shiny] ~~~ summon serp:articuno ~~~ serp:shiny
execute @s[tag=c145,tag=!shiny] ~~~ summon serp:zapdos ~~~ serp:normal
execute @s[tag=c145,tag=shiny] ~~~ summon serp:zapdos ~~~ serp:shiny
execute @s[tag=c146,tag=!shiny] ~~~ summon serp:moltres ~~~ serp:normal
execute @s[tag=c146,tag=shiny] ~~~ summon serp:moltres ~~~ serp:shiny
execute @s[tag=c147,tag=!shiny] ~~~ summon serp:dratini ~~~ serp:normal
execute @s[tag=c147,tag=shiny] ~~~ summon serp:dratini ~~~ serp:shiny
execute @s[tag=c148,tag=!shiny] ~~~ summon serp:dragonair ~~~ serp:normal
execute @s[tag=c148,tag=shiny] ~~~ summon serp:dragonair ~~~ serp:shiny
execute @s[tag=c149,tag=!shiny] ~~~ summon serp:dragonite ~~~ serp:normal
execute @s[tag=c149,tag=shiny] ~~~ summon serp:dragonite ~~~ serp:shiny
execute @s[tag=c150,tag=!shiny] ~~~ summon serp:mewtwo ~~~ serp:normal
execute @s[tag=c150,tag=shiny] ~~~ summon serp:mewtwo ~~~ serp:shiny
execute @s[tag=c151,tag=!shiny] ~~~ summon serp:mew ~~~ serp:normal
execute @s[tag=c151,tag=shiny] ~~~ summon serp:mew ~~~ serp:shiny
execute @s[tag=c152,tag=!shiny] ~~~ summon serp:chikorita ~~~ serp:normal
execute @s[tag=c152,tag=shiny] ~~~ summon serp:chikorita ~~~ serp:shiny
execute @s[tag=c153,tag=!shiny] ~~~ summon serp:bayleef ~~~ serp:normal
execute @s[tag=c153,tag=shiny] ~~~ summon serp:bayleef ~~~ serp:shiny
execute @s[tag=c154,tag=!shiny] ~~~ summon serp:meganium ~~~ serp:normal
execute @s[tag=c154,tag=shiny] ~~~ summon serp:meganium ~~~ serp:shiny
execute @s[tag=c155,tag=!shiny] ~~~ summon serp:cyndaquil ~~~ serp:normal
execute @s[tag=c155,tag=shiny] ~~~ summon serp:cyndaquil ~~~ serp:shiny
execute @s[tag=c156,tag=!shiny] ~~~ summon serp:quilava ~~~ serp:normal
execute @s[tag=c156,tag=shiny] ~~~ summon serp:quilava ~~~ serp:shiny
execute @s[tag=c157,tag=!shiny] ~~~ summon serp:typhlosion ~~~ serp:normal
execute @s[tag=c157,tag=shiny] ~~~ summon serp:typhlosion ~~~ serp:shiny
execute @s[tag=c158,tag=!shiny] ~~~ summon serp:totodile ~~~ serp:normal
execute @s[tag=c158,tag=shiny] ~~~ summon serp:totodile ~~~ serp:shiny
execute @s[tag=c159,tag=!shiny] ~~~ summon serp:croconaw ~~~ serp:normal
execute @s[tag=c159,tag=shiny] ~~~ summon serp:croconaw ~~~ serp:shiny
execute @s[tag=c160,tag=!shiny] ~~~ summon serp:feraligatr ~~~ serp:normal
execute @s[tag=c160,tag=shiny] ~~~ summon serp:feraligatr ~~~ serp:shiny
execute @s[tag=c161,tag=!shiny] ~~~ summon serp:sentret ~~~ serp:normal
execute @s[tag=c161,tag=shiny] ~~~ summon serp:sentret ~~~ serp:shiny
execute @s[tag=c162,tag=!shiny] ~~~ summon serp:furret ~~~ serp:normal
execute @s[tag=c162,tag=shiny] ~~~ summon serp:furret ~~~ serp:shiny
execute @s[tag=c163,tag=!shiny] ~~~ summon serp:hoothoot ~~~ serp:normal
execute @s[tag=c163,tag=shiny] ~~~ summon serp:hoothoot ~~~ serp:shiny
execute @s[tag=c164,tag=!shiny] ~~~ summon serp:noctowl ~~~ serp:normal
execute @s[tag=c164,tag=shiny] ~~~ summon serp:noctowl ~~~ serp:shiny
execute @s[tag=c165,tag=!shiny] ~~~ summon serp:ledyba ~~~ serp:normal
execute @s[tag=c165,tag=shiny] ~~~ summon serp:ledyba ~~~ serp:shiny
execute @s[tag=c166,tag=!shiny] ~~~ summon serp:ledian ~~~ serp:normal
execute @s[tag=c166,tag=shiny] ~~~ summon serp:ledian ~~~ serp:shiny
execute @s[tag=c167,tag=!shiny] ~~~ summon serp:spinarak ~~~ serp:normal
execute @s[tag=c167,tag=shiny] ~~~ summon serp:spinarak ~~~ serp:shiny
execute @s[tag=c168,tag=!shiny] ~~~ summon serp:ariados ~~~ serp:normal
execute @s[tag=c168,tag=shiny] ~~~ summon serp:ariados ~~~ serp:shiny
execute @s[tag=c169,tag=!shiny] ~~~ summon serp:crobat ~~~ serp:normal
execute @s[tag=c169,tag=shiny] ~~~ summon serp:crobat ~~~ serp:shiny
execute @s[tag=c170,tag=!shiny] ~~~ summon serp:chinchou ~~~ serp:normal
execute @s[tag=c170,tag=shiny] ~~~ summon serp:chinchou ~~~ serp:shiny
execute @s[tag=c171,tag=!shiny] ~~~ summon serp:lanturn ~~~ serp:normal
execute @s[tag=c171,tag=shiny] ~~~ summon serp:lanturn ~~~ serp:shiny
execute @s[tag=c172,tag=!shiny] ~~~ summon serp:pichu ~~~ serp:normal
execute @s[tag=c172,tag=shiny] ~~~ summon serp:pichu ~~~ serp:shiny
execute @s[tag=c173,tag=!shiny] ~~~ summon serp:cleffa ~~~ serp:normal
execute @s[tag=c173,tag=shiny] ~~~ summon serp:cleffa ~~~ serp:shiny
execute @s[tag=c174,tag=!shiny] ~~~ summon serp:igglybuff ~~~ serp:normal
execute @s[tag=c174,tag=shiny] ~~~ summon serp:igglybuff ~~~ serp:shiny
execute @s[tag=c175,tag=!shiny] ~~~ summon serp:togepi ~~~ serp:normal
execute @s[tag=c175,tag=shiny] ~~~ summon serp:togepi ~~~ serp:shiny
execute @s[tag=c176,tag=!shiny] ~~~ summon serp:togetic ~~~ serp:normal
execute @s[tag=c176,tag=shiny] ~~~ summon serp:togetic ~~~ serp:shiny
execute @s[tag=c177,tag=!shiny] ~~~ summon serp:natu ~~~ serp:normal
execute @s[tag=c177,tag=shiny] ~~~ summon serp:natu ~~~ serp:shiny
execute @s[tag=c178,tag=!shiny] ~~~ summon serp:xatu ~~~ serp:normal
execute @s[tag=c178,tag=shiny] ~~~ summon serp:xatu ~~~ serp:shiny
execute @s[tag=c179,tag=!shiny] ~~~ summon serp:mareep ~~~ serp:normal
execute @s[tag=c179,tag=shiny] ~~~ summon serp:mareep ~~~ serp:shiny
execute @s[tag=c180,tag=!shiny] ~~~ summon serp:flaaffy ~~~ serp:normal
execute @s[tag=c180,tag=shiny] ~~~ summon serp:flaaffy ~~~ serp:shiny
execute @s[tag=c181,tag=!shiny] ~~~ summon serp:ampharos ~~~ serp:normal
execute @s[tag=c181,tag=shiny] ~~~ summon serp:ampharos ~~~ serp:shiny
execute @s[tag=c182,tag=!shiny] ~~~ summon serp:bellossom ~~~ serp:normal
execute @s[tag=c182,tag=shiny] ~~~ summon serp:bellossom ~~~ serp:shiny
execute @s[tag=c183,tag=!shiny] ~~~ summon serp:marill ~~~ serp:normal
execute @s[tag=c183,tag=shiny] ~~~ summon serp:marill ~~~ serp:shiny
execute @s[tag=c184,tag=!shiny] ~~~ summon serp:azumarill ~~~ serp:normal
execute @s[tag=c184,tag=shiny] ~~~ summon serp:azumarill ~~~ serp:shiny
execute @s[tag=c185,tag=!shiny] ~~~ summon serp:sudowoodo ~~~ serp:normal
execute @s[tag=c185,tag=shiny] ~~~ summon serp:sudowoodo ~~~ serp:shiny
execute @s[tag=c186,tag=!shiny] ~~~ summon serp:politoed ~~~ serp:normal
execute @s[tag=c186,tag=shiny] ~~~ summon serp:politoed ~~~ serp:shiny
execute @s[tag=c187,tag=!shiny] ~~~ summon serp:hoppip ~~~ serp:normal
execute @s[tag=c187,tag=shiny] ~~~ summon serp:hoppip ~~~ serp:shiny
execute @s[tag=c188,tag=!shiny] ~~~ summon serp:skiploom ~~~ serp:normal
execute @s[tag=c188,tag=shiny] ~~~ summon serp:skiploom ~~~ serp:shiny
execute @s[tag=c189,tag=!shiny] ~~~ summon serp:jumpluff ~~~ serp:normal
execute @s[tag=c189,tag=shiny] ~~~ summon serp:jumpluff ~~~ serp:shiny
execute @s[tag=c190,tag=!shiny] ~~~ summon serp:aipom ~~~ serp:normal
execute @s[tag=c190,tag=shiny] ~~~ summon serp:aipom ~~~ serp:shiny
execute @s[tag=c191,tag=!shiny] ~~~ summon serp:sunkern ~~~ serp:normal
execute @s[tag=c191,tag=shiny] ~~~ summon serp:sunkern ~~~ serp:shiny
execute @s[tag=c192,tag=!shiny] ~~~ summon serp:sunflora ~~~ serp:normal
execute @s[tag=c192,tag=shiny] ~~~ summon serp:sunflora ~~~ serp:shiny
execute @s[tag=c193,tag=!shiny] ~~~ summon serp:yanma ~~~ serp:normal
execute @s[tag=c193,tag=shiny] ~~~ summon serp:yanma ~~~ serp:shiny
execute @s[tag=c194,tag=!shiny] ~~~ summon serp:wooper ~~~ serp:normal
execute @s[tag=c194,tag=shiny] ~~~ summon serp:wooper ~~~ serp:shiny
execute @s[tag=c195,tag=!shiny] ~~~ summon serp:quagsire ~~~ serp:normal
execute @s[tag=c195,tag=shiny] ~~~ summon serp:quagsire ~~~ serp:shiny
execute @s[tag=c196,tag=!shiny] ~~~ summon serp:espeon ~~~ serp:normal
execute @s[tag=c196,tag=shiny] ~~~ summon serp:espeon ~~~ serp:shiny
execute @s[tag=c197,tag=!shiny] ~~~ summon serp:umbreon ~~~ serp:normal
execute @s[tag=c197,tag=shiny] ~~~ summon serp:umbreon ~~~ serp:shiny
execute @s[tag=c198,tag=!shiny] ~~~ summon serp:murkrow ~~~ serp:normal
execute @s[tag=c198,tag=shiny] ~~~ summon serp:murkrow ~~~ serp:shiny
execute @s[tag=c199,tag=!shiny] ~~~ summon serp:slowking ~~~ serp:normal
execute @s[tag=c199,tag=shiny] ~~~ summon serp:slowking ~~~ serp:shiny
execute @s[tag=c200,tag=!shiny] ~~~ summon serp:misdreavus ~~~ serp:normal
execute @s[tag=c200,tag=shiny] ~~~ summon serp:misdreavus ~~~ serp:shiny
execute @s[tag=c201,tag=!shiny] ~~~ summon serp:unown ~~~ serp:normal
execute @s[tag=c201,tag=shiny] ~~~ summon serp:unown ~~~ serp:shiny
execute @s[tag=c202,tag=!shiny] ~~~ summon serp:wobbuffet ~~~ serp:normal
execute @s[tag=c202,tag=shiny] ~~~ summon serp:wobbuffet ~~~ serp:shiny
execute @s[tag=c203,tag=!shiny] ~~~ summon serp:girafarig ~~~ serp:normal
execute @s[tag=c203,tag=shiny] ~~~ summon serp:girafarig ~~~ serp:shiny
execute @s[tag=c204,tag=!shiny] ~~~ summon serp:pineco ~~~ serp:normal
execute @s[tag=c204,tag=shiny] ~~~ summon serp:pineco ~~~ serp:shiny
execute @s[tag=c205,tag=!shiny] ~~~ summon serp:forretress ~~~ serp:normal
execute @s[tag=c205,tag=shiny] ~~~ summon serp:forretress ~~~ serp:shiny
execute @s[tag=c206,tag=!shiny] ~~~ summon serp:dunsparce ~~~ serp:normal
execute @s[tag=c206,tag=shiny] ~~~ summon serp:dunsparce ~~~ serp:shiny
execute @s[tag=c207,tag=!shiny] ~~~ summon serp:gligar ~~~ serp:normal
execute @s[tag=c207,tag=shiny] ~~~ summon serp:gligar ~~~ serp:shiny
execute @s[tag=c208,tag=!shiny] ~~~ summon serp:steelix ~~~ serp:normal
execute @s[tag=c208,tag=shiny] ~~~ summon serp:steelix ~~~ serp:shiny
execute @s[tag=c209,tag=!shiny] ~~~ summon serp:snubbull ~~~ serp:normal
execute @s[tag=c209,tag=shiny] ~~~ summon serp:snubbull ~~~ serp:shiny
execute @s[tag=c210,tag=!shiny] ~~~ summon serp:granbull ~~~ serp:normal
execute @s[tag=c210,tag=shiny] ~~~ summon serp:granbull ~~~ serp:shiny
execute @s[tag=c211,tag=!shiny] ~~~ summon serp:qwilfish ~~~ serp:normal
execute @s[tag=c211,tag=shiny] ~~~ summon serp:qwilfish ~~~ serp:shiny
execute @s[tag=c212,tag=!shiny] ~~~ summon serp:scizor ~~~ serp:normal
execute @s[tag=c212,tag=shiny] ~~~ summon serp:scizor ~~~ serp:shiny
execute @s[tag=c213,tag=!shiny] ~~~ summon serp:shuckle ~~~ serp:normal
execute @s[tag=c213,tag=shiny] ~~~ summon serp:shuckle ~~~ serp:shiny
execute @s[tag=c214,tag=!shiny] ~~~ summon serp:heracross ~~~ serp:normal
execute @s[tag=c214,tag=shiny] ~~~ summon serp:heracross ~~~ serp:shiny
execute @s[tag=c215,tag=!shiny] ~~~ summon serp:sneasel ~~~ serp:normal
execute @s[tag=c215,tag=shiny] ~~~ summon serp:sneasel ~~~ serp:shiny
execute @s[tag=c216,tag=!shiny] ~~~ summon serp:teddiursa ~~~ serp:normal
execute @s[tag=c216,tag=shiny] ~~~ summon serp:teddiursa ~~~ serp:shiny
execute @s[tag=c217,tag=!shiny] ~~~ summon serp:ursaring ~~~ serp:normal
execute @s[tag=c217,tag=shiny] ~~~ summon serp:ursaring ~~~ serp:shiny
execute @s[tag=c218,tag=!shiny] ~~~ summon serp:slugma ~~~ serp:normal
execute @s[tag=c218,tag=shiny] ~~~ summon serp:slugma ~~~ serp:shiny
execute @s[tag=c219,tag=!shiny] ~~~ summon serp:magcargo ~~~ serp:normal
execute @s[tag=c219,tag=shiny] ~~~ summon serp:magcargo ~~~ serp:shiny
execute @s[tag=c220,tag=!shiny] ~~~ summon serp:swinub ~~~ serp:normal
execute @s[tag=c220,tag=shiny] ~~~ summon serp:swinub ~~~ serp:shiny
execute @s[tag=c221,tag=!shiny] ~~~ summon serp:piloswine ~~~ serp:normal
execute @s[tag=c221,tag=shiny] ~~~ summon serp:piloswine ~~~ serp:shiny
execute @s[tag=c222,tag=!shiny] ~~~ summon serp:corsola ~~~ serp:normal
execute @s[tag=c222,tag=shiny] ~~~ summon serp:corsola ~~~ serp:shiny
execute @s[tag=c223,tag=!shiny] ~~~ summon serp:remoraid ~~~ serp:normal
execute @s[tag=c223,tag=shiny] ~~~ summon serp:remoraid ~~~ serp:shiny
execute @s[tag=c224,tag=!shiny] ~~~ summon serp:octillery ~~~ serp:normal
execute @s[tag=c224,tag=shiny] ~~~ summon serp:octillery ~~~ serp:shiny
execute @s[tag=c225,tag=!shiny] ~~~ summon serp:delibird ~~~ serp:normal
execute @s[tag=c225,tag=shiny] ~~~ summon serp:delibird ~~~ serp:shiny
execute @s[tag=c226,tag=!shiny] ~~~ summon serp:mantine ~~~ serp:normal
execute @s[tag=c226,tag=shiny] ~~~ summon serp:mantine ~~~ serp:shiny
execute @s[tag=c227,tag=!shiny] ~~~ summon serp:skarmory ~~~ serp:normal
execute @s[tag=c227,tag=shiny] ~~~ summon serp:skarmory ~~~ serp:shiny
execute @s[tag=c228,tag=!shiny] ~~~ summon serp:houndour ~~~ serp:normal
execute @s[tag=c228,tag=shiny] ~~~ summon serp:houndour ~~~ serp:shiny
execute @s[tag=c229,tag=!shiny] ~~~ summon serp:houndoom ~~~ serp:normal
execute @s[tag=c229,tag=shiny] ~~~ summon serp:houndoom ~~~ serp:shiny
execute @s[tag=c230,tag=!shiny] ~~~ summon serp:kingdra ~~~ serp:normal
execute @s[tag=c230,tag=shiny] ~~~ summon serp:kingdra ~~~ serp:shiny
execute @s[tag=c231,tag=!shiny] ~~~ summon serp:phanpy ~~~ serp:normal
execute @s[tag=c231,tag=shiny] ~~~ summon serp:phanpy ~~~ serp:shiny
execute @s[tag=c232,tag=!shiny] ~~~ summon serp:donphan ~~~ serp:normal
execute @s[tag=c232,tag=shiny] ~~~ summon serp:donphan ~~~ serp:shiny
execute @s[tag=c233,tag=!shiny] ~~~ summon serp:porygon2 ~~~ serp:normal
execute @s[tag=c233,tag=shiny] ~~~ summon serp:porygon2 ~~~ serp:shiny
execute @s[tag=c234,tag=!shiny] ~~~ summon serp:stantler ~~~ serp:normal
execute @s[tag=c234,tag=shiny] ~~~ summon serp:stantler ~~~ serp:shiny
execute @s[tag=c235,tag=!shiny] ~~~ summon serp:smeargle ~~~ serp:normal
execute @s[tag=c235,tag=shiny] ~~~ summon serp:smeargle ~~~ serp:shiny
execute @s[tag=c236,tag=!shiny] ~~~ summon serp:tyrogue ~~~ serp:normal
execute @s[tag=c236,tag=shiny] ~~~ summon serp:tyrogue ~~~ serp:shiny
execute @s[tag=c237,tag=!shiny] ~~~ summon serp:hitmontop ~~~ serp:normal
execute @s[tag=c237,tag=shiny] ~~~ summon serp:hitmontop ~~~ serp:shiny
execute @s[tag=c238,tag=!shiny] ~~~ summon serp:smoochum ~~~ serp:normal
execute @s[tag=c238,tag=shiny] ~~~ summon serp:smoochum ~~~ serp:shiny
execute @s[tag=c239,tag=!shiny] ~~~ summon serp:elekid ~~~ serp:normal
execute @s[tag=c239,tag=shiny] ~~~ summon serp:elekid ~~~ serp:shiny
execute @s[tag=c240,tag=!shiny] ~~~ summon serp:magby ~~~ serp:normal
execute @s[tag=c240,tag=shiny] ~~~ summon serp:magby ~~~ serp:shiny
execute @s[tag=c241,tag=!shiny] ~~~ summon serp:miltank ~~~ serp:normal
execute @s[tag=c241,tag=shiny] ~~~ summon serp:miltank ~~~ serp:shiny
execute @s[tag=c242,tag=!shiny] ~~~ summon serp:blissey ~~~ serp:normal
execute @s[tag=c242,tag=shiny] ~~~ summon serp:blissey ~~~ serp:shiny
execute @s[tag=c243,tag=!shiny] ~~~ summon serp:raikou ~~~ serp:normal
execute @s[tag=c243,tag=shiny] ~~~ summon serp:raikou ~~~ serp:shiny
execute @s[tag=c244,tag=!shiny] ~~~ summon serp:entei ~~~ serp:normal
execute @s[tag=c244,tag=shiny] ~~~ summon serp:entei ~~~ serp:shiny
execute @s[tag=c245,tag=!shiny] ~~~ summon serp:suicune ~~~ serp:normal
execute @s[tag=c245,tag=shiny] ~~~ summon serp:suicune ~~~ serp:shiny
execute @s[tag=c246,tag=!shiny] ~~~ summon serp:larvitar ~~~ serp:normal
execute @s[tag=c246,tag=shiny] ~~~ summon serp:larvitar ~~~ serp:shiny
execute @s[tag=c247,tag=!shiny] ~~~ summon serp:pupitar ~~~ serp:normal
execute @s[tag=c247,tag=shiny] ~~~ summon serp:pupitar ~~~ serp:shiny
execute @s[tag=c248,tag=!shiny] ~~~ summon serp:tyranitar ~~~ serp:normal
execute @s[tag=c248,tag=shiny] ~~~ summon serp:tyranitar ~~~ serp:shiny
execute @s[tag=c249,tag=!shiny] ~~~ summon serp:lugia ~~~ serp:normal
execute @s[tag=c249,tag=shiny] ~~~ summon serp:lugia ~~~ serp:shiny
execute @s[tag=c250,tag=!shiny] ~~~ summon serp:hooh ~~~ serp:normal
execute @s[tag=c250,tag=shiny] ~~~ summon serp:hooh ~~~ serp:shiny
execute @s[tag=c251,tag=!shiny] ~~~ summon serp:celebi ~~~ serp:normal
execute @s[tag=c251,tag=shiny] ~~~ summon serp:celebi ~~~ serp:shiny



damage @e[r=3,c=1] 10 lava entity @e[r=3,c=1]