tellraw @p {"rawtext":[{"translate":"ball.catch"}]}
playsound serp.pokeball.capture @p

execute @s[tag=c1,tag=!shiny] ~~~ give @p serp:bulbasaur
execute @s[tag=c1,tag=shiny] ~~~ give @p serp:bulbasaurs
execute @s[tag=c1] ~~~ tag @p p1
execute @s[tag=c2,tag=!shiny] ~~~ give @p serp:ivysaur
execute @s[tag=c2,tag=shiny] ~~~ give @p serp:ivysaurs
execute @s[tag=c2] ~~~ tag @p p1
execute @s[tag=c3,tag=!shiny] ~~~ give @p serp:venusaur
execute @s[tag=c3,tag=shiny] ~~~ give @p serp:venusaurs
execute @s[tag=c3] ~~~ tag @p p1
execute @s[tag=c4,tag=!shiny] ~~~ give @p serp:charmander
execute @s[tag=c4,tag=shiny] ~~~ give @p serp:charmanders
execute @s[tag=c4] ~~~ tag @p p2
execute @s[tag=c5,tag=!shiny] ~~~ give @p serp:charmeleon
execute @s[tag=c5,tag=shiny] ~~~ give @p serp:charmeleons
execute @s[tag=c5] ~~~ tag @p p2
execute @s[tag=c6,tag=!shiny] ~~~ give @p serp:charizard
execute @s[tag=c6,tag=shiny] ~~~ give @p serp:charizards
execute @s[tag=c6] ~~~ tag @p p2
execute @s[tag=c7,tag=!shiny] ~~~ give @p serp:squirtle
execute @s[tag=c7,tag=shiny] ~~~ give @p serp:squirtles
execute @s[tag=c7] ~~~ tag @p p3
execute @s[tag=c8,tag=!shiny] ~~~ give @p serp:wartortle
execute @s[tag=c8,tag=shiny] ~~~ give @p serp:wartortles
execute @s[tag=c8] ~~~ tag @p p3
execute @s[tag=c9,tag=!shiny] ~~~ give @p serp:blastoise
execute @s[tag=c9,tag=shiny] ~~~ give @p serp:blastoises
execute @s[tag=c9] ~~~ tag @p p3
execute @s[tag=c10,tag=!shiny] ~~~ give @p serp:caterpie
execute @s[tag=c10,tag=shiny] ~~~ give @p serp:caterpies
execute @s[tag=c10] ~~~ tag @p p4
execute @s[tag=c11,tag=!shiny] ~~~ give @p serp:metapod
execute @s[tag=c11,tag=shiny] ~~~ give @p serp:metapods
execute @s[tag=c11] ~~~ tag @p p4
execute @s[tag=c12,tag=!shiny] ~~~ give @p serp:butterfree
execute @s[tag=c12,tag=shiny] ~~~ give @p serp:butterfrees
execute @s[tag=c12] ~~~ tag @p p4
execute @s[tag=c13,tag=!shiny] ~~~ give @p serp:weedle
execute @s[tag=c13,tag=shiny] ~~~ give @p serp:weedles
execute @s[tag=c13] ~~~ tag @p p5
execute @s[tag=c14,tag=!shiny] ~~~ give @p serp:kakuna
execute @s[tag=c14,tag=shiny] ~~~ give @p serp:kakunas
execute @s[tag=c14] ~~~ tag @p p5
execute @s[tag=c15,tag=!shiny] ~~~ give @p serp:beedrill
execute @s[tag=c15,tag=shiny] ~~~ give @p serp:beedrills
execute @s[tag=c15] ~~~ tag @p p5
execute @s[tag=c16,tag=!shiny] ~~~ give @p serp:pidgey
execute @s[tag=c16,tag=shiny] ~~~ give @p serp:pidgeys
execute @s[tag=c16] ~~~ tag @p p6
execute @s[tag=c17,tag=!shiny] ~~~ give @p serp:pidgeotto
execute @s[tag=c17,tag=shiny] ~~~ give @p serp:pidgeottos
execute @s[tag=c17] ~~~ tag @p p6
execute @s[tag=c18,tag=!shiny] ~~~ give @p serp:pidgeot
execute @s[tag=c18,tag=shiny] ~~~ give @p serp:pidgeots
execute @s[tag=c18] ~~~ tag @p p6
execute @s[tag=c19,tag=!shiny] ~~~ give @p serp:rattata
execute @s[tag=c19,tag=shiny] ~~~ give @p serp:rattatas
execute @s[tag=c19] ~~~ tag @p p7
execute @s[tag=c20,tag=!shiny] ~~~ give @p serp:raticate
execute @s[tag=c20,tag=shiny] ~~~ give @p serp:raticates
execute @s[tag=c20] ~~~ tag @p p7
execute @s[tag=c21,tag=!shiny] ~~~ give @p serp:spearow
execute @s[tag=c21,tag=shiny] ~~~ give @p serp:spearows
execute @s[tag=c21] ~~~ tag @p p8
execute @s[tag=c22,tag=!shiny] ~~~ give @p serp:fearow
execute @s[tag=c22,tag=shiny] ~~~ give @p serp:fearows
execute @s[tag=c22] ~~~ tag @p p8
execute @s[tag=c23,tag=!shiny] ~~~ give @p serp:ekans
execute @s[tag=c23,tag=shiny] ~~~ give @p serp:ekanss
execute @s[tag=c23] ~~~ tag @p p9
execute @s[tag=c24,tag=!shiny] ~~~ give @p serp:arbok
execute @s[tag=c24,tag=shiny] ~~~ give @p serp:arboks
execute @s[tag=c24] ~~~ tag @p p9
execute @s[tag=c25,tag=!shiny] ~~~ give @p serp:pikachu
execute @s[tag=c25,tag=shiny] ~~~ give @p serp:pikachus
execute @s[tag=c25] ~~~ tag @p p10
execute @s[tag=c26,tag=!shiny] ~~~ give @p serp:raichu
execute @s[tag=c26,tag=shiny] ~~~ give @p serp:raichus
execute @s[tag=c26] ~~~ tag @p p10
execute @s[tag=c27,tag=!shiny] ~~~ give @p serp:sandshrew
execute @s[tag=c27,tag=shiny] ~~~ give @p serp:sandshrews
execute @s[tag=c27] ~~~ tag @p p11
execute @s[tag=c28,tag=!shiny] ~~~ give @p serp:sandslash
execute @s[tag=c28,tag=shiny] ~~~ give @p serp:sandslashs
execute @s[tag=c28] ~~~ tag @p p11
execute @s[tag=c29,tag=!shiny] ~~~ give @p serp:nidoranh
execute @s[tag=c29,tag=shiny] ~~~ give @p serp:nidoranhs
execute @s[tag=c29] ~~~ tag @p p12
execute @s[tag=c30,tag=!shiny] ~~~ give @p serp:nidorina
execute @s[tag=c30,tag=shiny] ~~~ give @p serp:nidorinas
execute @s[tag=c30] ~~~ tag @p p12
execute @s[tag=c31,tag=!shiny] ~~~ give @p serp:nidoqueen
execute @s[tag=c31,tag=shiny] ~~~ give @p serp:nidoqueens
execute @s[tag=c31] ~~~ tag @p p12
execute @s[tag=c32,tag=!shiny] ~~~ give @p serp:nidoranm
execute @s[tag=c32,tag=shiny] ~~~ give @p serp:nidoranms
execute @s[tag=c32] ~~~ tag @p p13
execute @s[tag=c33,tag=!shiny] ~~~ give @p serp:nidorino
execute @s[tag=c33,tag=shiny] ~~~ give @p serp:nidorinos
execute @s[tag=c33] ~~~ tag @p p13
execute @s[tag=c34,tag=!shiny] ~~~ give @p serp:nidoking
execute @s[tag=c34,tag=shiny] ~~~ give @p serp:nidokings
execute @s[tag=c34] ~~~ tag @p p13
execute @s[tag=c35,tag=!shiny] ~~~ give @p serp:clefairy
execute @s[tag=c35,tag=shiny] ~~~ give @p serp:clefairys
execute @s[tag=c35] ~~~ tag @p p14
execute @s[tag=c36,tag=!shiny] ~~~ give @p serp:clefable
execute @s[tag=c36,tag=shiny] ~~~ give @p serp:clefables
execute @s[tag=c36] ~~~ tag @p p14
execute @s[tag=c37,tag=!shiny] ~~~ give @p serp:vulpix
execute @s[tag=c37,tag=shiny] ~~~ give @p serp:vulpixs
execute @s[tag=c37] ~~~ tag @p p15
execute @s[tag=c38,tag=!shiny] ~~~ give @p serp:ninetales
execute @s[tag=c38,tag=shiny] ~~~ give @p serp:ninetaless
execute @s[tag=c38] ~~~ tag @p p15
execute @s[tag=c39,tag=!shiny] ~~~ give @p serp:jigglypuff
execute @s[tag=c39,tag=shiny] ~~~ give @p serp:jigglypuffs
execute @s[tag=c39] ~~~ tag @p p16
execute @s[tag=c40,tag=!shiny] ~~~ give @p serp:wigglytuff
execute @s[tag=c40,tag=shiny] ~~~ give @p serp:wigglytuffs
execute @s[tag=c40] ~~~ tag @p p16
execute @s[tag=c41,tag=!shiny] ~~~ give @p serp:zubat
execute @s[tag=c41,tag=shiny] ~~~ give @p serp:zubats
execute @s[tag=c41] ~~~ tag @p p17
execute @s[tag=c42,tag=!shiny] ~~~ give @p serp:golbat
execute @s[tag=c42,tag=shiny] ~~~ give @p serp:golbats
execute @s[tag=c42] ~~~ tag @p p17
execute @s[tag=c43,tag=!shiny] ~~~ give @p serp:oddish
execute @s[tag=c43,tag=shiny] ~~~ give @p serp:oddishs
execute @s[tag=c43] ~~~ tag @p p18
execute @s[tag=c44,tag=!shiny] ~~~ give @p serp:gloom
execute @s[tag=c44,tag=shiny] ~~~ give @p serp:glooms
execute @s[tag=c44] ~~~ tag @p p18
execute @s[tag=c45,tag=!shiny] ~~~ give @p serp:vileplume
execute @s[tag=c45,tag=shiny] ~~~ give @p serp:vileplumes
execute @s[tag=c45] ~~~ tag @p p18
execute @s[tag=c46,tag=!shiny] ~~~ give @p serp:paras
execute @s[tag=c46,tag=shiny] ~~~ give @p serp:parass
execute @s[tag=c46] ~~~ tag @p p19
execute @s[tag=c47,tag=!shiny] ~~~ give @p serp:parasect
execute @s[tag=c47,tag=shiny] ~~~ give @p serp:parasects
execute @s[tag=c47] ~~~ tag @p p19
execute @s[tag=c48,tag=!shiny] ~~~ give @p serp:venonat
execute @s[tag=c48,tag=shiny] ~~~ give @p serp:venonats
execute @s[tag=c48] ~~~ tag @p p20
execute @s[tag=c49,tag=!shiny] ~~~ give @p serp:venomoth
execute @s[tag=c49,tag=shiny] ~~~ give @p serp:venomoths
execute @s[tag=c49] ~~~ tag @p p20
execute @s[tag=c50,tag=!shiny] ~~~ give @p serp:diglett
execute @s[tag=c50,tag=shiny] ~~~ give @p serp:digletts
execute @s[tag=c50] ~~~ tag @p p21
execute @s[tag=c51,tag=!shiny] ~~~ give @p serp:dugtrio
execute @s[tag=c51,tag=shiny] ~~~ give @p serp:dugtrios
execute @s[tag=c51] ~~~ tag @p p21
execute @s[tag=c52,tag=!shiny] ~~~ give @p serp:meowth
execute @s[tag=c52,tag=shiny] ~~~ give @p serp:meowths
execute @s[tag=c52] ~~~ tag @p p22
execute @s[tag=c53,tag=!shiny] ~~~ give @p serp:persian
execute @s[tag=c53,tag=shiny] ~~~ give @p serp:persians
execute @s[tag=c53] ~~~ tag @p p22
execute @s[tag=c54,tag=!shiny] ~~~ give @p serp:psyduck
execute @s[tag=c54,tag=shiny] ~~~ give @p serp:psyducks
execute @s[tag=c54] ~~~ tag @p p23
execute @s[tag=c55,tag=!shiny] ~~~ give @p serp:golduck
execute @s[tag=c55,tag=shiny] ~~~ give @p serp:golducks
execute @s[tag=c55] ~~~ tag @p p23
execute @s[tag=c56,tag=!shiny] ~~~ give @p serp:mankey
execute @s[tag=c56,tag=shiny] ~~~ give @p serp:mankeys
execute @s[tag=c56] ~~~ tag @p p24
execute @s[tag=c57,tag=!shiny] ~~~ give @p serp:primeape
execute @s[tag=c57,tag=shiny] ~~~ give @p serp:primeapes
execute @s[tag=c57] ~~~ tag @p p24
execute @s[tag=c58,tag=!shiny] ~~~ give @p serp:growlithe
execute @s[tag=c58,tag=shiny] ~~~ give @p serp:growlithes
execute @s[tag=c58] ~~~ tag @p p25
execute @s[tag=c59,tag=!shiny] ~~~ give @p serp:arcanine
execute @s[tag=c59,tag=shiny] ~~~ give @p serp:arcanines
execute @s[tag=c59] ~~~ tag @p p25
execute @s[tag=c60,tag=!shiny] ~~~ give @p serp:poliwag
execute @s[tag=c60,tag=shiny] ~~~ give @p serp:poliwags
execute @s[tag=c60] ~~~ tag @p p26
execute @s[tag=c61,tag=!shiny] ~~~ give @p serp:poliwhirl
execute @s[tag=c61,tag=shiny] ~~~ give @p serp:poliwhirls
execute @s[tag=c61] ~~~ tag @p p26
execute @s[tag=c62,tag=!shiny] ~~~ give @p serp:poliwrath
execute @s[tag=c62,tag=shiny] ~~~ give @p serp:poliwraths
execute @s[tag=c62] ~~~ tag @p p26
execute @s[tag=c63,tag=!shiny] ~~~ give @p serp:abra
execute @s[tag=c63,tag=shiny] ~~~ give @p serp:abras
execute @s[tag=c63] ~~~ tag @p p27
execute @s[tag=c64,tag=!shiny] ~~~ give @p serp:kadabra
execute @s[tag=c64,tag=shiny] ~~~ give @p serp:kadabras
execute @s[tag=c64] ~~~ tag @p p27
execute @s[tag=c65,tag=!shiny] ~~~ give @p serp:alakazam
execute @s[tag=c65,tag=shiny] ~~~ give @p serp:alakazams
execute @s[tag=c65] ~~~ tag @p p27
execute @s[tag=c66,tag=!shiny] ~~~ give @p serp:machop
execute @s[tag=c66,tag=shiny] ~~~ give @p serp:machops
execute @s[tag=c66] ~~~ tag @p p28
execute @s[tag=c67,tag=!shiny] ~~~ give @p serp:machoke
execute @s[tag=c67,tag=shiny] ~~~ give @p serp:machokes
execute @s[tag=c67] ~~~ tag @p p28
execute @s[tag=c68,tag=!shiny] ~~~ give @p serp:machamp
execute @s[tag=c68,tag=shiny] ~~~ give @p serp:machamps
execute @s[tag=c68] ~~~ tag @p p28
execute @s[tag=c69,tag=!shiny] ~~~ give @p serp:bellsprout
execute @s[tag=c69,tag=shiny] ~~~ give @p serp:bellsprouts
execute @s[tag=c69] ~~~ tag @p p29
execute @s[tag=c70,tag=!shiny] ~~~ give @p serp:weepinbell
execute @s[tag=c70,tag=shiny] ~~~ give @p serp:weepinbells
execute @s[tag=c70] ~~~ tag @p p29
execute @s[tag=c71,tag=!shiny] ~~~ give @p serp:victreebel
execute @s[tag=c71,tag=shiny] ~~~ give @p serp:victreebels
execute @s[tag=c71] ~~~ tag @p p29
execute @s[tag=c72,tag=!shiny] ~~~ give @p serp:tentacool
execute @s[tag=c72,tag=shiny] ~~~ give @p serp:tentacools
execute @s[tag=c72] ~~~ tag @p p30
execute @s[tag=c73,tag=!shiny] ~~~ give @p serp:tentacruel
execute @s[tag=c73,tag=shiny] ~~~ give @p serp:tentacruels
execute @s[tag=c73] ~~~ tag @p p30
execute @s[tag=c74,tag=!shiny] ~~~ give @p serp:geodude
execute @s[tag=c74,tag=shiny] ~~~ give @p serp:geodudes
execute @s[tag=c74] ~~~ tag @p p31
execute @s[tag=c75,tag=!shiny] ~~~ give @p serp:graveler
execute @s[tag=c75,tag=shiny] ~~~ give @p serp:gravelers
execute @s[tag=c75] ~~~ tag @p p31
execute @s[tag=c76,tag=!shiny] ~~~ give @p serp:golem
execute @s[tag=c76,tag=shiny] ~~~ give @p serp:golems
execute @s[tag=c76] ~~~ tag @p p31
execute @s[tag=c77,tag=!shiny] ~~~ give @p serp:ponyta
execute @s[tag=c77,tag=shiny] ~~~ give @p serp:ponytas
execute @s[tag=c77] ~~~ tag @p p32
execute @s[tag=c78,tag=!shiny] ~~~ give @p serp:rapidash
execute @s[tag=c78,tag=shiny] ~~~ give @p serp:rapidashs
execute @s[tag=c78] ~~~ tag @p p32
execute @s[tag=c79,tag=!shiny] ~~~ give @p serp:slowpoke
execute @s[tag=c79,tag=shiny] ~~~ give @p serp:slowpokes
execute @s[tag=c79] ~~~ tag @p p33
execute @s[tag=c80,tag=!shiny] ~~~ give @p serp:slowbro
execute @s[tag=c80,tag=shiny] ~~~ give @p serp:slowbros
execute @s[tag=c80] ~~~ tag @p p33
execute @s[tag=c81,tag=!shiny] ~~~ give @p serp:magnemite
execute @s[tag=c81,tag=shiny] ~~~ give @p serp:magnemites
execute @s[tag=c81] ~~~ tag @p p34
execute @s[tag=c82,tag=!shiny] ~~~ give @p serp:magneton
execute @s[tag=c82,tag=shiny] ~~~ give @p serp:magnetons
execute @s[tag=c82] ~~~ tag @p p34
execute @s[tag=c83,tag=!shiny] ~~~ give @p serp:farfetchd
execute @s[tag=c83,tag=shiny] ~~~ give @p serp:farfetchds
execute @s[tag=c83] ~~~ tag @p p35
execute @s[tag=c84,tag=!shiny] ~~~ give @p serp:doduo
execute @s[tag=c84,tag=shiny] ~~~ give @p serp:doduos
execute @s[tag=c84] ~~~ tag @p p36
execute @s[tag=c85,tag=!shiny] ~~~ give @p serp:dodrio
execute @s[tag=c85,tag=shiny] ~~~ give @p serp:dodrios
execute @s[tag=c85] ~~~ tag @p p36
execute @s[tag=c86,tag=!shiny] ~~~ give @p serp:seel
execute @s[tag=c86,tag=shiny] ~~~ give @p serp:seels
execute @s[tag=c86] ~~~ tag @p p37
execute @s[tag=c87,tag=!shiny] ~~~ give @p serp:dewgong
execute @s[tag=c87,tag=shiny] ~~~ give @p serp:dewgongs
execute @s[tag=c87] ~~~ tag @p p37
execute @s[tag=c88,tag=!shiny] ~~~ give @p serp:grimer
execute @s[tag=c88,tag=shiny] ~~~ give @p serp:grimers
execute @s[tag=c88] ~~~ tag @p p38
execute @s[tag=c89,tag=!shiny] ~~~ give @p serp:muk
execute @s[tag=c89,tag=shiny] ~~~ give @p serp:muks
execute @s[tag=c89] ~~~ tag @p p38
execute @s[tag=c90,tag=!shiny] ~~~ give @p serp:shellder
execute @s[tag=c90,tag=shiny] ~~~ give @p serp:shellders
execute @s[tag=c90] ~~~ tag @p p39
execute @s[tag=c91,tag=!shiny] ~~~ give @p serp:cloyster
execute @s[tag=c91,tag=shiny] ~~~ give @p serp:cloysters
execute @s[tag=c91] ~~~ tag @p p39
execute @s[tag=c92,tag=!shiny] ~~~ give @p serp:gastly
execute @s[tag=c92,tag=shiny] ~~~ give @p serp:gastlys
execute @s[tag=c92] ~~~ tag @p p40
execute @s[tag=c93,tag=!shiny] ~~~ give @p serp:haunter
execute @s[tag=c93,tag=shiny] ~~~ give @p serp:haunters
execute @s[tag=c93] ~~~ tag @p p40
execute @s[tag=c94,tag=!shiny] ~~~ give @p serp:gengar
execute @s[tag=c94,tag=shiny] ~~~ give @p serp:gengars
execute @s[tag=c94] ~~~ tag @p p40
execute @s[tag=c95,tag=!shiny] ~~~ give @p serp:onix
execute @s[tag=c95,tag=shiny] ~~~ give @p serp:onixs
execute @s[tag=c95] ~~~ tag @p p41
execute @s[tag=c96,tag=!shiny] ~~~ give @p serp:drowzee
execute @s[tag=c96,tag=shiny] ~~~ give @p serp:drowzees
execute @s[tag=c96] ~~~ tag @p p42
execute @s[tag=c97,tag=!shiny] ~~~ give @p serp:hypno
execute @s[tag=c97,tag=shiny] ~~~ give @p serp:hypnos
execute @s[tag=c97] ~~~ tag @p p42
execute @s[tag=c98,tag=!shiny] ~~~ give @p serp:krabby
execute @s[tag=c98,tag=shiny] ~~~ give @p serp:krabbys
execute @s[tag=c98] ~~~ tag @p p43
execute @s[tag=c99,tag=!shiny] ~~~ give @p serp:kingler
execute @s[tag=c99,tag=shiny] ~~~ give @p serp:kinglers
execute @s[tag=c99] ~~~ tag @p p43
execute @s[tag=c100,tag=!shiny] ~~~ give @p serp:voltorb
execute @s[tag=c100,tag=shiny] ~~~ give @p serp:voltorbs
execute @s[tag=c100] ~~~ tag @p p44
execute @s[tag=c101,tag=!shiny] ~~~ give @p serp:electrode
execute @s[tag=c101,tag=shiny] ~~~ give @p serp:electrodes
execute @s[tag=c101] ~~~ tag @p p44
execute @s[tag=c102,tag=!shiny] ~~~ give @p serp:exeggcute
execute @s[tag=c102,tag=shiny] ~~~ give @p serp:exeggcutes
execute @s[tag=c102] ~~~ tag @p p45
execute @s[tag=c103,tag=!shiny] ~~~ give @p serp:exeggutor
execute @s[tag=c103,tag=shiny] ~~~ give @p serp:exeggutors
execute @s[tag=c103] ~~~ tag @p p45
execute @s[tag=c104,tag=!shiny] ~~~ give @p serp:cubone
execute @s[tag=c104,tag=shiny] ~~~ give @p serp:cubones
execute @s[tag=c104] ~~~ tag @p p46
execute @s[tag=c105,tag=!shiny] ~~~ give @p serp:marowak
execute @s[tag=c105,tag=shiny] ~~~ give @p serp:marowaks
execute @s[tag=c105] ~~~ tag @p p46
execute @s[tag=c106,tag=!shiny] ~~~ give @p serp:hitmonlee
execute @s[tag=c106,tag=shiny] ~~~ give @p serp:hitmonlees
execute @s[tag=c106] ~~~ tag @p p47
execute @s[tag=c107,tag=!shiny] ~~~ give @p serp:hitmonchan
execute @s[tag=c107,tag=shiny] ~~~ give @p serp:hitmonchans
execute @s[tag=c107] ~~~ tag @p p47
execute @s[tag=c108,tag=!shiny] ~~~ give @p serp:lickitung
execute @s[tag=c108,tag=shiny] ~~~ give @p serp:lickitungs
execute @s[tag=c108] ~~~ tag @p p48
execute @s[tag=c109,tag=!shiny] ~~~ give @p serp:koffing
execute @s[tag=c109,tag=shiny] ~~~ give @p serp:koffings
execute @s[tag=c109] ~~~ tag @p p49
execute @s[tag=c110,tag=!shiny] ~~~ give @p serp:weezing
execute @s[tag=c110,tag=shiny] ~~~ give @p serp:weezings
execute @s[tag=c110] ~~~ tag @p p49
execute @s[tag=c111,tag=!shiny] ~~~ give @p serp:rhyhorn
execute @s[tag=c111,tag=shiny] ~~~ give @p serp:rhyhorns
execute @s[tag=c111] ~~~ tag @p p50
execute @s[tag=c112,tag=!shiny] ~~~ give @p serp:rhydon
execute @s[tag=c112,tag=shiny] ~~~ give @p serp:rhydons
execute @s[tag=c112] ~~~ tag @p p50
execute @s[tag=c113,tag=!shiny] ~~~ give @p serp:chansey
execute @s[tag=c113,tag=shiny] ~~~ give @p serp:chanseys
execute @s[tag=c113] ~~~ tag @p p51
execute @s[tag=c114,tag=!shiny] ~~~ give @p serp:tangela
execute @s[tag=c114,tag=shiny] ~~~ give @p serp:tangelas
execute @s[tag=c114] ~~~ tag @p p52
execute @s[tag=c115,tag=!shiny] ~~~ give @p serp:kangaskhan
execute @s[tag=c115,tag=shiny] ~~~ give @p serp:kangaskhans
execute @s[tag=c115] ~~~ tag @p p53
execute @s[tag=c116,tag=!shiny] ~~~ give @p serp:horsea
execute @s[tag=c116,tag=shiny] ~~~ give @p serp:horseas
execute @s[tag=c116] ~~~ tag @p p54
execute @s[tag=c117,tag=!shiny] ~~~ give @p serp:seadra
execute @s[tag=c117,tag=shiny] ~~~ give @p serp:seadras
execute @s[tag=c117] ~~~ tag @p p54
execute @s[tag=c118,tag=!shiny] ~~~ give @p serp:goldeen
execute @s[tag=c118,tag=shiny] ~~~ give @p serp:goldeens
execute @s[tag=c118] ~~~ tag @p p55
execute @s[tag=c119,tag=!shiny] ~~~ give @p serp:seaking
execute @s[tag=c119,tag=shiny] ~~~ give @p serp:seakings
execute @s[tag=c119] ~~~ tag @p p55
execute @s[tag=c120,tag=!shiny] ~~~ give @p serp:staryu
execute @s[tag=c120,tag=shiny] ~~~ give @p serp:staryus
execute @s[tag=c120] ~~~ tag @p p56
execute @s[tag=c121,tag=!shiny] ~~~ give @p serp:starmie
execute @s[tag=c121,tag=shiny] ~~~ give @p serp:starmies
execute @s[tag=c121] ~~~ tag @p p56
execute @s[tag=c122,tag=!shiny] ~~~ give @p serp:mrmime
execute @s[tag=c122,tag=shiny] ~~~ give @p serp:mrmimes
execute @s[tag=c122] ~~~ tag @p p57
execute @s[tag=c123,tag=!shiny] ~~~ give @p serp:scyther
execute @s[tag=c123,tag=shiny] ~~~ give @p serp:scythers
execute @s[tag=c123] ~~~ tag @p p58
execute @s[tag=c124,tag=!shiny] ~~~ give @p serp:jynx
execute @s[tag=c124,tag=shiny] ~~~ give @p serp:jynxs
execute @s[tag=c124] ~~~ tag @p p59
execute @s[tag=c125,tag=!shiny] ~~~ give @p serp:electabuzz
execute @s[tag=c125,tag=shiny] ~~~ give @p serp:electabuzzs
execute @s[tag=c125] ~~~ tag @p p60
execute @s[tag=c126,tag=!shiny] ~~~ give @p serp:magmar
execute @s[tag=c126,tag=shiny] ~~~ give @p serp:magmars
execute @s[tag=c126] ~~~ tag @p p61
execute @s[tag=c127,tag=!shiny] ~~~ give @p serp:pinsir
execute @s[tag=c127,tag=shiny] ~~~ give @p serp:pinsirs
execute @s[tag=c127] ~~~ tag @p p62
execute @s[tag=c128,tag=!shiny] ~~~ give @p serp:tauros
execute @s[tag=c128,tag=shiny] ~~~ give @p serp:tauross
execute @s[tag=c128] ~~~ tag @p p63
execute @s[tag=c129,tag=!shiny] ~~~ give @p serp:magikarp
execute @s[tag=c129,tag=shiny] ~~~ give @p serp:magikarps
execute @s[tag=c129] ~~~ tag @p p64
execute @s[tag=c130,tag=!shiny] ~~~ give @p serp:gyarados
execute @s[tag=c130,tag=shiny] ~~~ give @p serp:gyaradoss
execute @s[tag=c130] ~~~ tag @p p64
execute @s[tag=c131,tag=!shiny] ~~~ give @p serp:lapras
execute @s[tag=c131,tag=shiny] ~~~ give @p serp:laprass
execute @s[tag=c131] ~~~ tag @p p65
execute @s[tag=c132,tag=!shiny] ~~~ give @p serp:ditto
execute @s[tag=c132,tag=shiny] ~~~ give @p serp:dittos
execute @s[tag=c132] ~~~ tag @p p66
execute @s[tag=c133,tag=!shiny] ~~~ give @p serp:eevee
execute @s[tag=c133,tag=shiny] ~~~ give @p serp:eevees
execute @s[tag=c133] ~~~ tag @p p67
execute @s[tag=c134,tag=!shiny] ~~~ give @p serp:vaporeon
execute @s[tag=c134,tag=shiny] ~~~ give @p serp:vaporeons
execute @s[tag=c134] ~~~ tag @p p67
execute @s[tag=c135,tag=!shiny] ~~~ give @p serp:jolteon
execute @s[tag=c135,tag=shiny] ~~~ give @p serp:jolteons
execute @s[tag=c135] ~~~ tag @p p67
execute @s[tag=c136,tag=!shiny] ~~~ give @p serp:flareon
execute @s[tag=c136,tag=shiny] ~~~ give @p serp:flareons
execute @s[tag=c136] ~~~ tag @p p67
execute @s[tag=c137,tag=!shiny] ~~~ give @p serp:porygon
execute @s[tag=c137,tag=shiny] ~~~ give @p serp:porygons
execute @s[tag=c137] ~~~ tag @p p68
execute @s[tag=c138,tag=!shiny] ~~~ give @p serp:omanyte
execute @s[tag=c138,tag=shiny] ~~~ give @p serp:omanytes
execute @s[tag=c138] ~~~ tag @p p69
execute @s[tag=c139,tag=!shiny] ~~~ give @p serp:omastar
execute @s[tag=c139,tag=shiny] ~~~ give @p serp:omastars
execute @s[tag=c139] ~~~ tag @p p69
execute @s[tag=c140,tag=!shiny] ~~~ give @p serp:kabuto
execute @s[tag=c140,tag=shiny] ~~~ give @p serp:kabutos
execute @s[tag=c140] ~~~ tag @p p70
execute @s[tag=c141,tag=!shiny] ~~~ give @p serp:kabutops
execute @s[tag=c141,tag=shiny] ~~~ give @p serp:kabutopss
execute @s[tag=c141] ~~~ tag @p p70
execute @s[tag=c142,tag=!shiny] ~~~ give @p serp:aerodactyl
execute @s[tag=c142,tag=shiny] ~~~ give @p serp:aerodactyls
execute @s[tag=c142] ~~~ tag @p p71
execute @s[tag=c143,tag=!shiny] ~~~ give @p serp:snorlax
execute @s[tag=c143,tag=shiny] ~~~ give @p serp:snorlaxs
execute @s[tag=c143] ~~~ tag @p p72
execute @s[tag=c144,tag=!shiny] ~~~ give @p serp:articuno
execute @s[tag=c144,tag=shiny] ~~~ give @p serp:articunos
execute @s[tag=c144] ~~~ tag @p p73
execute @s[tag=c145,tag=!shiny] ~~~ give @p serp:zapdos
execute @s[tag=c145,tag=shiny] ~~~ give @p serp:zapdoss
execute @s[tag=c145] ~~~ tag @p p74
execute @s[tag=c146,tag=!shiny] ~~~ give @p serp:moltres
execute @s[tag=c146,tag=shiny] ~~~ give @p serp:moltress
execute @s[tag=c146] ~~~ tag @p p75
execute @s[tag=c147,tag=!shiny] ~~~ give @p serp:dratini
execute @s[tag=c147,tag=shiny] ~~~ give @p serp:dratinis
execute @s[tag=c147] ~~~ tag @p p76
execute @s[tag=c148,tag=!shiny] ~~~ give @p serp:dragonair
execute @s[tag=c148,tag=shiny] ~~~ give @p serp:dragonairs
execute @s[tag=c148] ~~~ tag @p p76
execute @s[tag=c149,tag=!shiny] ~~~ give @p serp:dragonite
execute @s[tag=c149,tag=shiny] ~~~ give @p serp:dragonites
execute @s[tag=c149] ~~~ tag @p p76
execute @s[tag=c150,tag=!shiny] ~~~ give @p serp:mewtwo
execute @s[tag=c150,tag=shiny] ~~~ give @p serp:mewtwos
execute @s[tag=c150] ~~~ tag @p p77
execute @s[tag=c151,tag=!shiny] ~~~ give @p serp:mew
execute @s[tag=c151,tag=shiny] ~~~ give @p serp:mews
execute @s[tag=c151] ~~~ tag @p p78
execute @s[tag=c152,tag=!shiny] ~~~ give @p serp:chikorita
execute @s[tag=c152,tag=shiny] ~~~ give @p serp:chikoritas
execute @s[tag=c152] ~~~ tag @p p79
execute @s[tag=c153,tag=!shiny] ~~~ give @p serp:bayleef
execute @s[tag=c153,tag=shiny] ~~~ give @p serp:bayleefs
execute @s[tag=c153] ~~~ tag @p p79
execute @s[tag=c154,tag=!shiny] ~~~ give @p serp:meganium
execute @s[tag=c154,tag=shiny] ~~~ give @p serp:meganiums
execute @s[tag=c154] ~~~ tag @p p79
execute @s[tag=c155,tag=!shiny] ~~~ give @p serp:cyndaquil
execute @s[tag=c155,tag=shiny] ~~~ give @p serp:cyndaquils
execute @s[tag=c155] ~~~ tag @p p80
execute @s[tag=c156,tag=!shiny] ~~~ give @p serp:quilava
execute @s[tag=c156,tag=shiny] ~~~ give @p serp:quilavas
execute @s[tag=c156] ~~~ tag @p p80
execute @s[tag=c157,tag=!shiny] ~~~ give @p serp:typhlosion
execute @s[tag=c157,tag=shiny] ~~~ give @p serp:typhlosions
execute @s[tag=c157] ~~~ tag @p p80
execute @s[tag=c158,tag=!shiny] ~~~ give @p serp:totodile
execute @s[tag=c158,tag=shiny] ~~~ give @p serp:totodiles
execute @s[tag=c158] ~~~ tag @p p81
execute @s[tag=c159,tag=!shiny] ~~~ give @p serp:croconaw
execute @s[tag=c159,tag=shiny] ~~~ give @p serp:croconaws
execute @s[tag=c159] ~~~ tag @p p81
execute @s[tag=c160,tag=!shiny] ~~~ give @p serp:feraligatr
execute @s[tag=c160,tag=shiny] ~~~ give @p serp:feraligatrs
execute @s[tag=c160] ~~~ tag @p p81
execute @s[tag=c161,tag=!shiny] ~~~ give @p serp:sentret
execute @s[tag=c161,tag=shiny] ~~~ give @p serp:sentrets
execute @s[tag=c161] ~~~ tag @p p82
execute @s[tag=c162,tag=!shiny] ~~~ give @p serp:furret
execute @s[tag=c162,tag=shiny] ~~~ give @p serp:furrets
execute @s[tag=c162] ~~~ tag @p p82
execute @s[tag=c163,tag=!shiny] ~~~ give @p serp:hoothoot
execute @s[tag=c163,tag=shiny] ~~~ give @p serp:hoothoots
execute @s[tag=c163] ~~~ tag @p p83
execute @s[tag=c164,tag=!shiny] ~~~ give @p serp:noctowl
execute @s[tag=c164,tag=shiny] ~~~ give @p serp:noctowls
execute @s[tag=c164] ~~~ tag @p p83
execute @s[tag=c165,tag=!shiny] ~~~ give @p serp:ledyba
execute @s[tag=c165,tag=shiny] ~~~ give @p serp:ledybas
execute @s[tag=c165] ~~~ tag @p p84
execute @s[tag=c166,tag=!shiny] ~~~ give @p serp:ledian
execute @s[tag=c166,tag=shiny] ~~~ give @p serp:ledians
execute @s[tag=c166] ~~~ tag @p p84
execute @s[tag=c167,tag=!shiny] ~~~ give @p serp:spinarak
execute @s[tag=c167,tag=shiny] ~~~ give @p serp:spinaraks
execute @s[tag=c167] ~~~ tag @p p85
execute @s[tag=c168,tag=!shiny] ~~~ give @p serp:ariados
execute @s[tag=c168,tag=shiny] ~~~ give @p serp:ariadoss
execute @s[tag=c168] ~~~ tag @p p85
execute @s[tag=c169,tag=!shiny] ~~~ give @p serp:crobat
execute @s[tag=c169,tag=shiny] ~~~ give @p serp:crobats
execute @s[tag=c169] ~~~ tag @p p17
execute @s[tag=c170,tag=!shiny] ~~~ give @p serp:chinchou
execute @s[tag=c170,tag=shiny] ~~~ give @p serp:chinchous
execute @s[tag=c170] ~~~ tag @p p86
execute @s[tag=c171,tag=!shiny] ~~~ give @p serp:lanturn
execute @s[tag=c171,tag=shiny] ~~~ give @p serp:lanturns
execute @s[tag=c171] ~~~ tag @p p86
execute @s[tag=c172,tag=!shiny] ~~~ give @p serp:pichu
execute @s[tag=c172,tag=shiny] ~~~ give @p serp:pichus
execute @s[tag=c172] ~~~ tag @p p10
execute @s[tag=c173,tag=!shiny] ~~~ give @p serp:cleffa
execute @s[tag=c173,tag=shiny] ~~~ give @p serp:cleffas
execute @s[tag=c173] ~~~ tag @p p14
execute @s[tag=c174,tag=!shiny] ~~~ give @p serp:igglybuff
execute @s[tag=c174,tag=shiny] ~~~ give @p serp:igglybuffs
execute @s[tag=c174] ~~~ tag @p p16
execute @s[tag=c175,tag=!shiny] ~~~ give @p serp:togepi
execute @s[tag=c175,tag=shiny] ~~~ give @p serp:togepis
execute @s[tag=c175] ~~~ tag @p p87
execute @s[tag=c176,tag=!shiny] ~~~ give @p serp:togetic
execute @s[tag=c176,tag=shiny] ~~~ give @p serp:togetics
execute @s[tag=c176] ~~~ tag @p p87
execute @s[tag=c177,tag=!shiny] ~~~ give @p serp:natu
execute @s[tag=c177,tag=shiny] ~~~ give @p serp:natus
execute @s[tag=c177] ~~~ tag @p p88
execute @s[tag=c178,tag=!shiny] ~~~ give @p serp:xatu
execute @s[tag=c178,tag=shiny] ~~~ give @p serp:xatus
execute @s[tag=c178] ~~~ tag @p p88
execute @s[tag=c179,tag=!shiny] ~~~ give @p serp:mareep
execute @s[tag=c179,tag=shiny] ~~~ give @p serp:mareeps
execute @s[tag=c179] ~~~ tag @p p89
execute @s[tag=c180,tag=!shiny] ~~~ give @p serp:flaaffy
execute @s[tag=c180,tag=shiny] ~~~ give @p serp:flaaffys
execute @s[tag=c180] ~~~ tag @p p89
execute @s[tag=c181,tag=!shiny] ~~~ give @p serp:ampharos
execute @s[tag=c181,tag=shiny] ~~~ give @p serp:amphaross
execute @s[tag=c181] ~~~ tag @p p89
execute @s[tag=c182,tag=!shiny] ~~~ give @p serp:bellossom
execute @s[tag=c182,tag=shiny] ~~~ give @p serp:bellossoms
execute @s[tag=c182] ~~~ tag @p p18
execute @s[tag=c183,tag=!shiny] ~~~ give @p serp:marill
execute @s[tag=c183,tag=shiny] ~~~ give @p serp:marills
execute @s[tag=c183] ~~~ tag @p p90
execute @s[tag=c184,tag=!shiny] ~~~ give @p serp:azumarill
execute @s[tag=c184,tag=shiny] ~~~ give @p serp:azumarills
execute @s[tag=c184] ~~~ tag @p p90
execute @s[tag=c185,tag=!shiny] ~~~ give @p serp:sudowoodo
execute @s[tag=c185,tag=shiny] ~~~ give @p serp:sudowoodos
execute @s[tag=c185] ~~~ tag @p p91
execute @s[tag=c186,tag=!shiny] ~~~ give @p serp:politoed
execute @s[tag=c186,tag=shiny] ~~~ give @p serp:politoeds
execute @s[tag=c186] ~~~ tag @p p26
execute @s[tag=c187,tag=!shiny] ~~~ give @p serp:hoppip
execute @s[tag=c187,tag=shiny] ~~~ give @p serp:hoppips
execute @s[tag=c187] ~~~ tag @p p92
execute @s[tag=c188,tag=!shiny] ~~~ give @p serp:skiploom
execute @s[tag=c188,tag=shiny] ~~~ give @p serp:skiplooms
execute @s[tag=c188] ~~~ tag @p p92
execute @s[tag=c189,tag=!shiny] ~~~ give @p serp:jumpluff
execute @s[tag=c189,tag=shiny] ~~~ give @p serp:jumpluffs
execute @s[tag=c189] ~~~ tag @p p92
execute @s[tag=c190,tag=!shiny] ~~~ give @p serp:aipom
execute @s[tag=c190,tag=shiny] ~~~ give @p serp:aipoms
execute @s[tag=c190] ~~~ tag @p p93
execute @s[tag=c191,tag=!shiny] ~~~ give @p serp:sunkern
execute @s[tag=c191,tag=shiny] ~~~ give @p serp:sunkerns
execute @s[tag=c191] ~~~ tag @p p94
execute @s[tag=c192,tag=!shiny] ~~~ give @p serp:sunflora
execute @s[tag=c192,tag=shiny] ~~~ give @p serp:sunfloras
execute @s[tag=c192] ~~~ tag @p p94
execute @s[tag=c193,tag=!shiny] ~~~ give @p serp:yanma
execute @s[tag=c193,tag=shiny] ~~~ give @p serp:yanmas
execute @s[tag=c193] ~~~ tag @p p95
execute @s[tag=c194,tag=!shiny] ~~~ give @p serp:wooper
execute @s[tag=c194,tag=shiny] ~~~ give @p serp:woopers
execute @s[tag=c194] ~~~ tag @p p96
execute @s[tag=c195,tag=!shiny] ~~~ give @p serp:quagsire
execute @s[tag=c195,tag=shiny] ~~~ give @p serp:quagsires
execute @s[tag=c195] ~~~ tag @p p96
execute @s[tag=c196,tag=!shiny] ~~~ give @p serp:espeon
execute @s[tag=c196,tag=shiny] ~~~ give @p serp:espeons
execute @s[tag=c196] ~~~ tag @p p67
execute @s[tag=c197,tag=!shiny] ~~~ give @p serp:umbreon
execute @s[tag=c197,tag=shiny] ~~~ give @p serp:umbreons
execute @s[tag=c197] ~~~ tag @p p67
execute @s[tag=c198,tag=!shiny] ~~~ give @p serp:murkrow
execute @s[tag=c198,tag=shiny] ~~~ give @p serp:murkrows
execute @s[tag=c198] ~~~ tag @p p97
execute @s[tag=c199,tag=!shiny] ~~~ give @p serp:slowking
execute @s[tag=c199,tag=shiny] ~~~ give @p serp:slowkings
execute @s[tag=c199] ~~~ tag @p p33
execute @s[tag=c200,tag=!shiny] ~~~ give @p serp:misdreavus
execute @s[tag=c200,tag=shiny] ~~~ give @p serp:misdreavuss
execute @s[tag=c200] ~~~ tag @p p98
execute @s[tag=c201,tag=!shiny] ~~~ give @p serp:unown
execute @s[tag=c201,tag=shiny] ~~~ give @p serp:unowns
execute @s[tag=c201] ~~~ tag @p p99
execute @s[tag=c202,tag=!shiny] ~~~ give @p serp:wobbuffet
execute @s[tag=c202,tag=shiny] ~~~ give @p serp:wobbuffets
execute @s[tag=c202] ~~~ tag @p p100
execute @s[tag=c203,tag=!shiny] ~~~ give @p serp:girafarig
execute @s[tag=c203,tag=shiny] ~~~ give @p serp:girafarigs
execute @s[tag=c203] ~~~ tag @p p101
execute @s[tag=c204,tag=!shiny] ~~~ give @p serp:pineco
execute @s[tag=c204,tag=shiny] ~~~ give @p serp:pinecos
execute @s[tag=c204] ~~~ tag @p p102
execute @s[tag=c205,tag=!shiny] ~~~ give @p serp:forretress
execute @s[tag=c205,tag=shiny] ~~~ give @p serp:forretresss
execute @s[tag=c205] ~~~ tag @p p102
execute @s[tag=c206,tag=!shiny] ~~~ give @p serp:dunsparce
execute @s[tag=c206,tag=shiny] ~~~ give @p serp:dunsparces
execute @s[tag=c206] ~~~ tag @p p103
execute @s[tag=c207,tag=!shiny] ~~~ give @p serp:gligar
execute @s[tag=c207,tag=shiny] ~~~ give @p serp:gligars
execute @s[tag=c207] ~~~ tag @p p104
execute @s[tag=c208,tag=!shiny] ~~~ give @p serp:steelix
execute @s[tag=c208,tag=shiny] ~~~ give @p serp:steelixs
execute @s[tag=c208] ~~~ tag @p p41
execute @s[tag=c209,tag=!shiny] ~~~ give @p serp:snubbull
execute @s[tag=c209,tag=shiny] ~~~ give @p serp:snubbulls
execute @s[tag=c209] ~~~ tag @p p105
execute @s[tag=c210,tag=!shiny] ~~~ give @p serp:granbull
execute @s[tag=c210,tag=shiny] ~~~ give @p serp:granbulls
execute @s[tag=c210] ~~~ tag @p p105
execute @s[tag=c211,tag=!shiny] ~~~ give @p serp:qwilfish
execute @s[tag=c211,tag=shiny] ~~~ give @p serp:qwilfishs
execute @s[tag=c211] ~~~ tag @p p106
execute @s[tag=c212,tag=!shiny] ~~~ give @p serp:scizor
execute @s[tag=c212,tag=shiny] ~~~ give @p serp:scizors
execute @s[tag=c212] ~~~ tag @p p58
execute @s[tag=c213,tag=!shiny] ~~~ give @p serp:shuckle
execute @s[tag=c213,tag=shiny] ~~~ give @p serp:shuckles
execute @s[tag=c213] ~~~ tag @p p107
execute @s[tag=c214,tag=!shiny] ~~~ give @p serp:heracross
execute @s[tag=c214,tag=shiny] ~~~ give @p serp:heracrosss
execute @s[tag=c214] ~~~ tag @p p108
execute @s[tag=c215,tag=!shiny] ~~~ give @p serp:sneasel
execute @s[tag=c215,tag=shiny] ~~~ give @p serp:sneasels
execute @s[tag=c215] ~~~ tag @p p109
execute @s[tag=c216,tag=!shiny] ~~~ give @p serp:teddiursa
execute @s[tag=c216,tag=shiny] ~~~ give @p serp:teddiursas
execute @s[tag=c216] ~~~ tag @p p110
execute @s[tag=c217,tag=!shiny] ~~~ give @p serp:ursaring
execute @s[tag=c217,tag=shiny] ~~~ give @p serp:ursarings
execute @s[tag=c217] ~~~ tag @p p110
execute @s[tag=c218,tag=!shiny] ~~~ give @p serp:slugma
execute @s[tag=c218,tag=shiny] ~~~ give @p serp:slugmas
execute @s[tag=c218] ~~~ tag @p p111
execute @s[tag=c219,tag=!shiny] ~~~ give @p serp:magcargo
execute @s[tag=c219,tag=shiny] ~~~ give @p serp:magcargos
execute @s[tag=c219] ~~~ tag @p p111
execute @s[tag=c220,tag=!shiny] ~~~ give @p serp:swinub
execute @s[tag=c220,tag=shiny] ~~~ give @p serp:swinubs
execute @s[tag=c220] ~~~ tag @p p112
execute @s[tag=c221,tag=!shiny] ~~~ give @p serp:piloswine
execute @s[tag=c221,tag=shiny] ~~~ give @p serp:piloswines
execute @s[tag=c221] ~~~ tag @p p112
execute @s[tag=c222,tag=!shiny] ~~~ give @p serp:corsola
execute @s[tag=c222,tag=shiny] ~~~ give @p serp:corsolas
execute @s[tag=c222] ~~~ tag @p p113
execute @s[tag=c223,tag=!shiny] ~~~ give @p serp:remoraid
execute @s[tag=c223,tag=shiny] ~~~ give @p serp:remoraids
execute @s[tag=c223] ~~~ tag @p p114
execute @s[tag=c224,tag=!shiny] ~~~ give @p serp:octillery
execute @s[tag=c224,tag=shiny] ~~~ give @p serp:octillerys
execute @s[tag=c224] ~~~ tag @p p114
execute @s[tag=c225,tag=!shiny] ~~~ give @p serp:delibird
execute @s[tag=c225,tag=shiny] ~~~ give @p serp:delibirds
execute @s[tag=c225] ~~~ tag @p p115
execute @s[tag=c226,tag=!shiny] ~~~ give @p serp:mantine
execute @s[tag=c226,tag=shiny] ~~~ give @p serp:mantines
execute @s[tag=c226] ~~~ tag @p p116
execute @s[tag=c227,tag=!shiny] ~~~ give @p serp:skarmory
execute @s[tag=c227,tag=shiny] ~~~ give @p serp:skarmorys
execute @s[tag=c227] ~~~ tag @p p117
execute @s[tag=c228,tag=!shiny] ~~~ give @p serp:houndour
execute @s[tag=c228,tag=shiny] ~~~ give @p serp:houndours
execute @s[tag=c228] ~~~ tag @p p118
execute @s[tag=c229,tag=!shiny] ~~~ give @p serp:houndoom
execute @s[tag=c229,tag=shiny] ~~~ give @p serp:houndooms
execute @s[tag=c229] ~~~ tag @p p118
execute @s[tag=c230,tag=!shiny] ~~~ give @p serp:kingdra
execute @s[tag=c230,tag=shiny] ~~~ give @p serp:kingdras
execute @s[tag=c230] ~~~ tag @p p54
execute @s[tag=c231,tag=!shiny] ~~~ give @p serp:phanpy
execute @s[tag=c231,tag=shiny] ~~~ give @p serp:phanpys
execute @s[tag=c231] ~~~ tag @p p119
execute @s[tag=c232,tag=!shiny] ~~~ give @p serp:donphan
execute @s[tag=c232,tag=shiny] ~~~ give @p serp:donphans
execute @s[tag=c232] ~~~ tag @p p119
execute @s[tag=c233,tag=!shiny] ~~~ give @p serp:porygon2
execute @s[tag=c233,tag=shiny] ~~~ give @p serp:porygon2s
execute @s[tag=c233] ~~~ tag @p p68
execute @s[tag=c234,tag=!shiny] ~~~ give @p serp:stantler
execute @s[tag=c234,tag=shiny] ~~~ give @p serp:stantlers
execute @s[tag=c234] ~~~ tag @p p120
execute @s[tag=c235,tag=!shiny] ~~~ give @p serp:smeargle
execute @s[tag=c235,tag=shiny] ~~~ give @p serp:smeargles
execute @s[tag=c235] ~~~ tag @p p121
execute @s[tag=c236,tag=!shiny] ~~~ give @p serp:tyrogue
execute @s[tag=c236,tag=shiny] ~~~ give @p serp:tyrogues
execute @s[tag=c236] ~~~ tag @p p47
execute @s[tag=c237,tag=!shiny] ~~~ give @p serp:hitmontop
execute @s[tag=c237,tag=shiny] ~~~ give @p serp:hitmontops
execute @s[tag=c237] ~~~ tag @p p47
execute @s[tag=c238,tag=!shiny] ~~~ give @p serp:smoochum
execute @s[tag=c238,tag=shiny] ~~~ give @p serp:smoochums
execute @s[tag=c238] ~~~ tag @p p59
execute @s[tag=c239,tag=!shiny] ~~~ give @p serp:elekid
execute @s[tag=c239,tag=shiny] ~~~ give @p serp:elekids
execute @s[tag=c239] ~~~ tag @p p60
execute @s[tag=c240,tag=!shiny] ~~~ give @p serp:magby
execute @s[tag=c240,tag=shiny] ~~~ give @p serp:magbys
execute @s[tag=c240] ~~~ tag @p p61
execute @s[tag=c241,tag=!shiny] ~~~ give @p serp:miltank
execute @s[tag=c241,tag=shiny] ~~~ give @p serp:miltanks
execute @s[tag=c241] ~~~ tag @p p122
execute @s[tag=c242,tag=!shiny] ~~~ give @p serp:blissey
execute @s[tag=c242,tag=shiny] ~~~ give @p serp:blisseys
execute @s[tag=c242] ~~~ tag @p p51
execute @s[tag=c243,tag=!shiny] ~~~ give @p serp:raikou
execute @s[tag=c243,tag=shiny] ~~~ give @p serp:raikous
execute @s[tag=c243] ~~~ tag @p p123
execute @s[tag=c244,tag=!shiny] ~~~ give @p serp:entei
execute @s[tag=c244,tag=shiny] ~~~ give @p serp:enteis
execute @s[tag=c244] ~~~ tag @p p124
execute @s[tag=c245,tag=!shiny] ~~~ give @p serp:suicune
execute @s[tag=c245,tag=shiny] ~~~ give @p serp:suicunes
execute @s[tag=c245] ~~~ tag @p p125
execute @s[tag=c246,tag=!shiny] ~~~ give @p serp:larvitar
execute @s[tag=c246,tag=shiny] ~~~ give @p serp:larvitars
execute @s[tag=c246] ~~~ tag @p p126
execute @s[tag=c247,tag=!shiny] ~~~ give @p serp:pupitar
execute @s[tag=c247,tag=shiny] ~~~ give @p serp:pupitars
execute @s[tag=c247] ~~~ tag @p p126
execute @s[tag=c248,tag=!shiny] ~~~ give @p serp:tyranitar
execute @s[tag=c248,tag=shiny] ~~~ give @p serp:tyranitars
execute @s[tag=c248] ~~~ tag @p p126
execute @s[tag=c249,tag=!shiny] ~~~ give @p serp:lugia
execute @s[tag=c249,tag=shiny] ~~~ give @p serp:lugias
execute @s[tag=c249] ~~~ tag @p p127
execute @s[tag=c250,tag=!shiny] ~~~ give @p serp:hooh
execute @s[tag=c250,tag=shiny] ~~~ give @p serp:hoohs
execute @s[tag=c250] ~~~ tag @p p128
execute @s[tag=c251,tag=!shiny] ~~~ give @p serp:celebi
execute @s[tag=c251,tag=shiny] ~~~ give @p serp:celebis
execute @s[tag=c251] ~~~ tag @p p129