tag @s remove bug
tag @s remove dark
tag @s remove dragon
tag @s remove electric
tag @s remove fairy
tag @s remove fight
tag @s remove fire
tag @s remove flying
tag @s remove ghost
tag @s remove grass
tag @s remove ground
tag @s remove ice
tag @s remove normal
tag @s remove poison
tag @s remove psychic
tag @s remove rock
tag @s remove steel
tag @s remove water
tag @s remove critic
tag @s remove on_turn