execute @p ~~~ execute @s[scores={spawn=..0}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=1}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s1
execute @p ~~~ execute @s[scores={spawn=-1}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s1
execute @p ~~~ execute @s[scores={spawn=2}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s2
execute @p ~~~ execute @s[scores={spawn=-2}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s2
execute @p ~~~ execute @s[scores={spawn=3}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s3
execute @p ~~~ execute @s[scores={spawn=-3}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s3
execute @p ~~~ execute @s[scores={spawn=4}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s4
execute @p ~~~ execute @s[scores={spawn=-4}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s4
execute @p ~~~ execute @s[scores={spawn=5}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s5
execute @p ~~~ execute @s[scores={spawn=-5}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s5
execute @p ~~~ execute @s[scores={spawn=6}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s6
execute @p ~~~ execute @s[scores={spawn=-6}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s6
execute @p ~~~ execute @s[scores={spawn=7}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s7
execute @p ~~~ execute @s[scores={spawn=-7}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s7
execute @p ~~~ execute @s[scores={spawn=8}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s8
execute @p ~~~ execute @s[scores={spawn=-8}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s8
execute @p ~~~ execute @s[scores={spawn=9}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s9
execute @p ~~~ execute @s[scores={spawn=-9}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s9
execute @p ~~~ execute @s[scores={spawn=10}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s10
execute @p ~~~ execute @s[scores={spawn=-10}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s10
execute @p ~~~ execute @s[scores={spawn=11}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s11
execute @p ~~~ execute @s[scores={spawn=-11}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s11
execute @p ~~~ execute @s[scores={spawn=12}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s12
execute @p ~~~ execute @s[scores={spawn=-12}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s12
execute @p ~~~ execute @s[scores={spawn=13}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s13
execute @p ~~~ execute @s[scores={spawn=-13}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s13
execute @p ~~~ execute @s[scores={spawn=14}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s14
execute @p ~~~ execute @s[scores={spawn=-14}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s14
execute @p ~~~ execute @s[scores={spawn=15}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s15
execute @p ~~~ execute @s[scores={spawn=-15}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s15
execute @p ~~~ execute @s[scores={spawn=16}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s16
execute @p ~~~ execute @s[scores={spawn=-16}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s16
execute @p ~~~ execute @s[scores={spawn=17}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s17
execute @p ~~~ execute @s[scores={spawn=-17}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s17
execute @p ~~~ execute @s[scores={spawn=18}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s18
execute @p ~~~ execute @s[scores={spawn=-18}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s18
execute @p ~~~ execute @s[scores={spawn=19}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s19
execute @p ~~~ execute @s[scores={spawn=-19}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s19
execute @p ~~~ execute @s[scores={spawn=20}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s20
execute @p ~~~ execute @s[scores={spawn=-20}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s20
execute @p ~~~ execute @s[scores={spawn=21}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s21
execute @p ~~~ execute @s[scores={spawn=-21}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s21
execute @p ~~~ execute @s[scores={spawn=22}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s22
execute @p ~~~ execute @s[scores={spawn=-22}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s22
execute @p ~~~ execute @s[scores={spawn=23}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s23
execute @p ~~~ execute @s[scores={spawn=-23}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s23
execute @p ~~~ execute @s[scores={spawn=24}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s24
execute @p ~~~ execute @s[scores={spawn=-24}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s24
execute @p ~~~ execute @s[scores={spawn=25}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s25
execute @p ~~~ execute @s[scores={spawn=-25}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s25
execute @p ~~~ execute @s[scores={spawn=26}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s26
execute @p ~~~ execute @s[scores={spawn=-26}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s26
execute @p ~~~ execute @s[scores={spawn=27}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s27
execute @p ~~~ execute @s[scores={spawn=-27}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s27
execute @p ~~~ execute @s[scores={spawn=28}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s28
execute @p ~~~ execute @s[scores={spawn=-28}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s28
execute @p ~~~ execute @s[scores={spawn=29}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s29
execute @p ~~~ execute @s[scores={spawn=-29}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s29
execute @p ~~~ execute @s[scores={spawn=30}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s30
execute @p ~~~ execute @s[scores={spawn=-30}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s30
execute @p ~~~ execute @s[scores={spawn=31}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s31
execute @p ~~~ execute @s[scores={spawn=-31}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s31
execute @p ~~~ execute @s[scores={spawn=32}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s32
execute @p ~~~ execute @s[scores={spawn=-32}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s32
execute @p ~~~ execute @s[scores={spawn=33}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s33
execute @p ~~~ execute @s[scores={spawn=-33}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s33
execute @p ~~~ execute @s[scores={spawn=34}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s34
execute @p ~~~ execute @s[scores={spawn=-34}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s34
execute @p ~~~ execute @s[scores={spawn=35}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s35
execute @p ~~~ execute @s[scores={spawn=-35}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s35
execute @p ~~~ execute @s[scores={spawn=36}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s36
execute @p ~~~ execute @s[scores={spawn=-36}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s36
execute @p ~~~ execute @s[scores={spawn=37}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s37
execute @p ~~~ execute @s[scores={spawn=-37}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s37
execute @p ~~~ execute @s[scores={spawn=38}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s38
execute @p ~~~ execute @s[scores={spawn=-38}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s38
execute @p ~~~ execute @s[scores={spawn=39}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s39
execute @p ~~~ execute @s[scores={spawn=-39}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s39
execute @p ~~~ execute @s[scores={spawn=40}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s40
execute @p ~~~ execute @s[scores={spawn=-40}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s40
execute @p ~~~ execute @s[scores={spawn=41}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s41
execute @p ~~~ execute @s[scores={spawn=-41}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s41
execute @p ~~~ execute @s[scores={spawn=42}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s42
execute @p ~~~ execute @s[scores={spawn=-42}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s42
execute @p ~~~ execute @s[scores={spawn=43}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s43
execute @p ~~~ execute @s[scores={spawn=-43}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s43
execute @p ~~~ execute @s[scores={spawn=44}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s44
execute @p ~~~ execute @s[scores={spawn=-44}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s44
execute @p ~~~ execute @s[scores={spawn=45}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s45
execute @p ~~~ execute @s[scores={spawn=-45}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s45
execute @p ~~~ execute @s[scores={spawn=46}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s46
execute @p ~~~ execute @s[scores={spawn=-46}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s46
execute @p ~~~ execute @s[scores={spawn=47}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s47
execute @p ~~~ execute @s[scores={spawn=-47}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s47
execute @p ~~~ execute @s[scores={spawn=48}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s48
execute @p ~~~ execute @s[scores={spawn=-48}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s48
execute @p ~~~ execute @s[scores={spawn=49}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s49
execute @p ~~~ execute @s[scores={spawn=-49}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s49
execute @p ~~~ execute @s[scores={spawn=50}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s50
execute @p ~~~ execute @s[scores={spawn=-50}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s50
execute @p ~~~ execute @s[scores={spawn=51}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s51
execute @p ~~~ execute @s[scores={spawn=-51}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s51
execute @p ~~~ execute @s[scores={spawn=52}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s52
execute @p ~~~ execute @s[scores={spawn=-52}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s52
execute @p ~~~ execute @s[scores={spawn=53}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s53
execute @p ~~~ execute @s[scores={spawn=-53}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s53
execute @p ~~~ execute @s[scores={spawn=54}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s54
execute @p ~~~ execute @s[scores={spawn=-54}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s54
execute @p ~~~ execute @s[scores={spawn=55}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s55
execute @p ~~~ execute @s[scores={spawn=-55}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s55
execute @p ~~~ execute @s[scores={spawn=56}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s56
execute @p ~~~ execute @s[scores={spawn=-56}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s56
execute @p ~~~ execute @s[scores={spawn=57}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s57
execute @p ~~~ execute @s[scores={spawn=-57}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s57
execute @p ~~~ execute @s[scores={spawn=58}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s58
execute @p ~~~ execute @s[scores={spawn=-58}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s58
execute @p ~~~ execute @s[scores={spawn=59}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s59
execute @p ~~~ execute @s[scores={spawn=-59}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s59
execute @p ~~~ execute @s[scores={spawn=60}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s60
execute @p ~~~ execute @s[scores={spawn=-60}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s60
execute @p ~~~ execute @s[scores={spawn=61}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s61
execute @p ~~~ execute @s[scores={spawn=-61}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s61
execute @p ~~~ execute @s[scores={spawn=62}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s62
execute @p ~~~ execute @s[scores={spawn=-62}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s62
execute @p ~~~ execute @s[scores={spawn=63}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s63
execute @p ~~~ execute @s[scores={spawn=-63}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s63
execute @p ~~~ execute @s[scores={spawn=64}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s64
execute @p ~~~ execute @s[scores={spawn=-64}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s64
execute @p ~~~ execute @s[scores={spawn=65}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s65
execute @p ~~~ execute @s[scores={spawn=-65}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s65
execute @p ~~~ execute @s[scores={spawn=66}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s66
execute @p ~~~ execute @s[scores={spawn=-66}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s66
execute @p ~~~ execute @s[scores={spawn=67}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s67
execute @p ~~~ execute @s[scores={spawn=-67}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s67
execute @p ~~~ execute @s[scores={spawn=68}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s68
execute @p ~~~ execute @s[scores={spawn=-68}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s68
execute @p ~~~ execute @s[scores={spawn=69}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s69
execute @p ~~~ execute @s[scores={spawn=-69}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s69
execute @p ~~~ execute @s[scores={spawn=70}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s70
execute @p ~~~ execute @s[scores={spawn=-70}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s70
execute @p ~~~ execute @s[scores={spawn=71}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s71
execute @p ~~~ execute @s[scores={spawn=-71}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s71
execute @p ~~~ execute @s[scores={spawn=72}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s72
execute @p ~~~ execute @s[scores={spawn=-72}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s72
execute @p ~~~ execute @s[scores={spawn=73}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s73
execute @p ~~~ execute @s[scores={spawn=-73}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s73
execute @p ~~~ execute @s[scores={spawn=74}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s74
execute @p ~~~ execute @s[scores={spawn=-74}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s74
execute @p ~~~ execute @s[scores={spawn=75}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s75
execute @p ~~~ execute @s[scores={spawn=-75}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s75
execute @p ~~~ execute @s[scores={spawn=76}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s76
execute @p ~~~ execute @s[scores={spawn=-76}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s76
execute @p ~~~ execute @s[scores={spawn=77}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s77
execute @p ~~~ execute @s[scores={spawn=-77}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s77
execute @p ~~~ execute @s[scores={spawn=78}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s78
execute @p ~~~ execute @s[scores={spawn=-78}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s78
execute @p ~~~ execute @s[scores={spawn=79}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s79
execute @p ~~~ execute @s[scores={spawn=-79}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s79
execute @p ~~~ execute @s[scores={spawn=80}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s80
execute @p ~~~ execute @s[scores={spawn=-80}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s80
execute @p ~~~ execute @s[scores={spawn=81}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s81
execute @p ~~~ execute @s[scores={spawn=-81}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s81
execute @p ~~~ execute @s[scores={spawn=82}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s82
execute @p ~~~ execute @s[scores={spawn=-82}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s82
execute @p ~~~ execute @s[scores={spawn=83}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s83
execute @p ~~~ execute @s[scores={spawn=-83}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s83
execute @p ~~~ execute @s[scores={spawn=84}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s84
execute @p ~~~ execute @s[scores={spawn=-84}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s84
execute @p ~~~ execute @s[scores={spawn=85}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s85
execute @p ~~~ execute @s[scores={spawn=-85}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s85
execute @p ~~~ execute @s[scores={spawn=86}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s86
execute @p ~~~ execute @s[scores={spawn=-86}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s86
execute @p ~~~ execute @s[scores={spawn=87}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s87
execute @p ~~~ execute @s[scores={spawn=-87}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s87
execute @p ~~~ execute @s[scores={spawn=88}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s88
execute @p ~~~ execute @s[scores={spawn=-88}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s88
execute @p ~~~ execute @s[scores={spawn=89}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s89
execute @p ~~~ execute @s[scores={spawn=-89}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s89
execute @p ~~~ execute @s[scores={spawn=90}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s90
execute @p ~~~ execute @s[scores={spawn=-90}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s90
execute @p ~~~ execute @s[scores={spawn=91}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s91
execute @p ~~~ execute @s[scores={spawn=-91}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s91
execute @p ~~~ execute @s[scores={spawn=92}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s92
execute @p ~~~ execute @s[scores={spawn=-92}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s92
execute @p ~~~ execute @s[scores={spawn=93}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s93
execute @p ~~~ execute @s[scores={spawn=-93}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s93
execute @p ~~~ execute @s[scores={spawn=94}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s94
execute @p ~~~ execute @s[scores={spawn=-94}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s94
execute @p ~~~ execute @s[scores={spawn=95}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s95
execute @p ~~~ execute @s[scores={spawn=-95}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s95
execute @p ~~~ execute @s[scores={spawn=96}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s96
execute @p ~~~ execute @s[scores={spawn=-96}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s96
execute @p ~~~ execute @s[scores={spawn=97}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s97
execute @p ~~~ execute @s[scores={spawn=-97}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s97
execute @p ~~~ execute @s[scores={spawn=98}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s98
execute @p ~~~ execute @s[scores={spawn=-98}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s98
execute @p ~~~ execute @s[scores={spawn=99}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s99
execute @p ~~~ execute @s[scores={spawn=-99}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s99
execute @p ~~~ execute @s[scores={spawn=101}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s101
execute @p ~~~ execute @s[scores={spawn=-101}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s101
execute @p ~~~ execute @s[scores={spawn=102}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s102
execute @p ~~~ execute @s[scores={spawn=-102}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s102
execute @p ~~~ execute @s[scores={spawn=103}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s103
execute @p ~~~ execute @s[scores={spawn=-103}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s103
execute @p ~~~ execute @s[scores={spawn=104}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s104
execute @p ~~~ execute @s[scores={spawn=-104}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s104
execute @p ~~~ execute @s[scores={spawn=105}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s105
execute @p ~~~ execute @s[scores={spawn=-105}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s105
execute @p ~~~ execute @s[scores={spawn=106}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s106
execute @p ~~~ execute @s[scores={spawn=-106}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s106
execute @p ~~~ execute @s[scores={spawn=107}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s107
execute @p ~~~ execute @s[scores={spawn=-107}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s107
execute @p ~~~ execute @s[scores={spawn=108}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s108
execute @p ~~~ execute @s[scores={spawn=-108}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s108
execute @p ~~~ execute @s[scores={spawn=109}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s109
execute @p ~~~ execute @s[scores={spawn=-109}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s109
execute @p ~~~ execute @s[scores={spawn=110}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s110
execute @p ~~~ execute @s[scores={spawn=-110}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s110
execute @p ~~~ execute @s[scores={spawn=111}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s111
execute @p ~~~ execute @s[scores={spawn=-111}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s111
execute @p ~~~ execute @s[scores={spawn=112}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s112
execute @p ~~~ execute @s[scores={spawn=-112}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s112
execute @p ~~~ execute @s[scores={spawn=113}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s113
execute @p ~~~ execute @s[scores={spawn=-113}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s113
execute @p ~~~ execute @s[scores={spawn=114}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s114
execute @p ~~~ execute @s[scores={spawn=-114}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s114
execute @p ~~~ execute @s[scores={spawn=115}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s115
execute @p ~~~ execute @s[scores={spawn=-115}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s115
execute @p ~~~ execute @s[scores={spawn=116}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s116
execute @p ~~~ execute @s[scores={spawn=-116}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s116
execute @p ~~~ execute @s[scores={spawn=117}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s117
execute @p ~~~ execute @s[scores={spawn=-117}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s117
execute @p ~~~ execute @s[scores={spawn=118}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s118
execute @p ~~~ execute @s[scores={spawn=-118}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s118
execute @p ~~~ execute @s[scores={spawn=119}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s119
execute @p ~~~ execute @s[scores={spawn=-119}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s119
execute @p ~~~ execute @s[scores={spawn=120}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s120
execute @p ~~~ execute @s[scores={spawn=-120}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s120
execute @p ~~~ execute @s[scores={spawn=121}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s121
execute @p ~~~ execute @s[scores={spawn=-121}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s121
execute @p ~~~ execute @s[scores={spawn=122}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s122
execute @p ~~~ execute @s[scores={spawn=-122}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s122
execute @p ~~~ execute @s[scores={spawn=123}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s123
execute @p ~~~ execute @s[scores={spawn=-123}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s123
execute @p ~~~ execute @s[scores={spawn=124}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s124
execute @p ~~~ execute @s[scores={spawn=-124}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s124
execute @p ~~~ execute @s[scores={spawn=125}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s125
execute @p ~~~ execute @s[scores={spawn=-125}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s125
execute @p ~~~ execute @s[scores={spawn=126}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s126
execute @p ~~~ execute @s[scores={spawn=-126}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s126
execute @p ~~~ execute @s[scores={spawn=127}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s127
execute @p ~~~ execute @s[scores={spawn=-127}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s127
execute @p ~~~ execute @s[scores={spawn=128}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s128
execute @p ~~~ execute @s[scores={spawn=-128}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s128
execute @p ~~~ execute @s[scores={spawn=129}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s129
execute @p ~~~ execute @s[scores={spawn=-129}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s129
execute @p ~~~ execute @s[scores={spawn=130}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s130
execute @p ~~~ execute @s[scores={spawn=-130}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s130
execute @p ~~~ execute @s[scores={spawn=131}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s131
execute @p ~~~ execute @s[scores={spawn=-131}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s131
execute @p ~~~ execute @s[scores={spawn=132}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s132
execute @p ~~~ execute @s[scores={spawn=-132}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s132
execute @p ~~~ execute @s[scores={spawn=133}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s133
execute @p ~~~ execute @s[scores={spawn=-133}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s133
execute @p ~~~ execute @s[scores={spawn=134}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s134
execute @p ~~~ execute @s[scores={spawn=-134}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s134
execute @p ~~~ execute @s[scores={spawn=135}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s135
execute @p ~~~ execute @s[scores={spawn=-135}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s135
execute @p ~~~ execute @s[scores={spawn=136}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s136
execute @p ~~~ execute @s[scores={spawn=-136}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s136
execute @p ~~~ execute @s[scores={spawn=137}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s137
execute @p ~~~ execute @s[scores={spawn=-137}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s137
execute @p ~~~ execute @s[scores={spawn=138}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s138
execute @p ~~~ execute @s[scores={spawn=-138}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s138
execute @p ~~~ execute @s[scores={spawn=139}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s139
execute @p ~~~ execute @s[scores={spawn=-139}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s139
execute @p ~~~ execute @s[scores={spawn=140}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s140
execute @p ~~~ execute @s[scores={spawn=-140}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s140
execute @p ~~~ execute @s[scores={spawn=141}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s141
execute @p ~~~ execute @s[scores={spawn=-141}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s141
execute @p ~~~ execute @s[scores={spawn=142}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s142
execute @p ~~~ execute @s[scores={spawn=-142}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s142
execute @p ~~~ execute @s[scores={spawn=143}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s143
execute @p ~~~ execute @s[scores={spawn=-143}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s143
execute @p ~~~ execute @s[scores={spawn=144}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s144
execute @p ~~~ execute @s[scores={spawn=-144}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s144
execute @p ~~~ execute @s[scores={spawn=145}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s145
execute @p ~~~ execute @s[scores={spawn=-145}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s145
execute @p ~~~ execute @s[scores={spawn=146}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s146
execute @p ~~~ execute @s[scores={spawn=-146}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s146
execute @p ~~~ execute @s[scores={spawn=147}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s147
execute @p ~~~ execute @s[scores={spawn=-147}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s147
execute @p ~~~ execute @s[scores={spawn=148}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s148
execute @p ~~~ execute @s[scores={spawn=-148}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s148
execute @p ~~~ execute @s[scores={spawn=149}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s149
execute @p ~~~ execute @s[scores={spawn=-149}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s149
execute @p ~~~ execute @s[scores={spawn=150}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s150
execute @p ~~~ execute @s[scores={spawn=-150}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s150
execute @p ~~~ execute @s[scores={spawn=151}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s151
execute @p ~~~ execute @s[scores={spawn=-151}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s151
execute @p ~~~ execute @s[scores={spawn=152}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s152
execute @p ~~~ execute @s[scores={spawn=-152}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s152
execute @p ~~~ execute @s[scores={spawn=153}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s153
execute @p ~~~ execute @s[scores={spawn=-153}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s153
execute @p ~~~ execute @s[scores={spawn=154}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s154
execute @p ~~~ execute @s[scores={spawn=-154}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-154}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s154
execute @p ~~~ execute @s[scores={spawn=155}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s155
execute @p ~~~ execute @s[scores={spawn=-155}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-155}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s155
execute @p ~~~ execute @s[scores={spawn=156}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s156
execute @p ~~~ execute @s[scores={spawn=-156}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-156}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s156
execute @p ~~~ execute @s[scores={spawn=157}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s157
execute @p ~~~ execute @s[scores={spawn=-157}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-157}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s157
execute @p ~~~ execute @s[scores={spawn=158}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s158
execute @p ~~~ execute @s[scores={spawn=-158}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-158}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s158
execute @p ~~~ execute @s[scores={spawn=159}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s159
execute @p ~~~ execute @s[scores={spawn=-159}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-159}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s159
execute @p ~~~ execute @s[scores={spawn=160}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s160
execute @p ~~~ execute @s[scores={spawn=-160}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-160}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s160
execute @p ~~~ execute @s[scores={spawn=161}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s161
execute @p ~~~ execute @s[scores={spawn=-161}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-161}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s161
execute @p ~~~ execute @s[scores={spawn=162}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s162
execute @p ~~~ execute @s[scores={spawn=-162}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-162}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s162
execute @p ~~~ execute @s[scores={spawn=163}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s163
execute @p ~~~ execute @s[scores={spawn=-163}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-163}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s163
execute @p ~~~ execute @s[scores={spawn=164}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s164
execute @p ~~~ execute @s[scores={spawn=-164}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-164}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s164
execute @p ~~~ execute @s[scores={spawn=165}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s165
execute @p ~~~ execute @s[scores={spawn=-165}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-165}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s165
execute @p ~~~ execute @s[scores={spawn=166}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s166
execute @p ~~~ execute @s[scores={spawn=-166}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-166}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s166
execute @p ~~~ execute @s[scores={spawn=167}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s167
execute @p ~~~ execute @s[scores={spawn=-167}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-167}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s167
execute @p ~~~ execute @s[scores={spawn=168}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s168
execute @p ~~~ execute @s[scores={spawn=-168}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-168}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s168
execute @p ~~~ execute @s[scores={spawn=169}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s169
execute @p ~~~ execute @s[scores={spawn=-169}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-169}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s169
execute @p ~~~ execute @s[scores={spawn=170}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s170
execute @p ~~~ execute @s[scores={spawn=-170}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-170}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s170
execute @p ~~~ execute @s[scores={spawn=171}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s171
execute @p ~~~ execute @s[scores={spawn=-171}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-171}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s171
execute @p ~~~ execute @s[scores={spawn=172}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s172
execute @p ~~~ execute @s[scores={spawn=-172}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-172}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s172
execute @p ~~~ execute @s[scores={spawn=173}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s173
execute @p ~~~ execute @s[scores={spawn=-173}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-173}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s173
execute @p ~~~ execute @s[scores={spawn=174}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s174
execute @p ~~~ execute @s[scores={spawn=-174}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-174}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s174
execute @p ~~~ execute @s[scores={spawn=175}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s175
execute @p ~~~ execute @s[scores={spawn=-175}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-175}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s175
execute @p ~~~ execute @s[scores={spawn=176}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s176
execute @p ~~~ execute @s[scores={spawn=-176}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-176}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s176
execute @p ~~~ execute @s[scores={spawn=177}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s177
execute @p ~~~ execute @s[scores={spawn=-177}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-177}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s177
execute @p ~~~ execute @s[scores={spawn=178}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s178
execute @p ~~~ execute @s[scores={spawn=-178}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-178}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s178
execute @p ~~~ execute @s[scores={spawn=179}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s179
execute @p ~~~ execute @s[scores={spawn=-179}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-179}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s179
execute @p ~~~ execute @s[scores={spawn=180}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s180
execute @p ~~~ execute @s[scores={spawn=-180}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-180}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s180
execute @p ~~~ execute @s[scores={spawn=181}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s181
execute @p ~~~ execute @s[scores={spawn=-181}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-181}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s181
execute @p ~~~ execute @s[scores={spawn=182}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s182
execute @p ~~~ execute @s[scores={spawn=-182}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-182}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s182
execute @p ~~~ execute @s[scores={spawn=183}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s183
execute @p ~~~ execute @s[scores={spawn=-183}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-183}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s183
execute @p ~~~ execute @s[scores={spawn=184}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s184
execute @p ~~~ execute @s[scores={spawn=-184}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-184}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s184
execute @p ~~~ execute @s[scores={spawn=185}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s185
execute @p ~~~ execute @s[scores={spawn=-185}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-185}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s185
execute @p ~~~ execute @s[scores={spawn=186}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s186
execute @p ~~~ execute @s[scores={spawn=-186}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-186}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s186
execute @p ~~~ execute @s[scores={spawn=187}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s187
execute @p ~~~ execute @s[scores={spawn=-187}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-187}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s187
execute @p ~~~ execute @s[scores={spawn=188}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s188
execute @p ~~~ execute @s[scores={spawn=-188}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-188}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s188
execute @p ~~~ execute @s[scores={spawn=189}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s189
execute @p ~~~ execute @s[scores={spawn=-189}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-189}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s189
execute @p ~~~ execute @s[scores={spawn=190}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s190
execute @p ~~~ execute @s[scores={spawn=-190}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-190}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s190
execute @p ~~~ execute @s[scores={spawn=191}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s191
execute @p ~~~ execute @s[scores={spawn=-191}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-191}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s191
execute @p ~~~ execute @s[scores={spawn=192}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s192
execute @p ~~~ execute @s[scores={spawn=-192}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-192}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s192
execute @p ~~~ execute @s[scores={spawn=193}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s193
execute @p ~~~ execute @s[scores={spawn=-193}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-193}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s193
execute @p ~~~ execute @s[scores={spawn=194}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s194
execute @p ~~~ execute @s[scores={spawn=-194}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-194}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s194
execute @p ~~~ execute @s[scores={spawn=195}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s195
execute @p ~~~ execute @s[scores={spawn=-195}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-195}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s195
execute @p ~~~ execute @s[scores={spawn=196}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s196
execute @p ~~~ execute @s[scores={spawn=-196}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-196}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s196
execute @p ~~~ execute @s[scores={spawn=197}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s197
execute @p ~~~ execute @s[scores={spawn=-197}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-197}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s197
execute @p ~~~ execute @s[scores={spawn=198}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s198
execute @p ~~~ execute @s[scores={spawn=-198}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-198}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s198
execute @p ~~~ execute @s[scores={spawn=199}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s199
execute @p ~~~ execute @s[scores={spawn=-199}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-199}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s199
execute @p ~~~ execute @s[scores={spawn=200}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s200
execute @p ~~~ execute @s[scores={spawn=-200}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-200}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s200

execute @p ~~~ execute @s[scores={spawn=201}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s201
execute @p ~~~ execute @s[scores={spawn=-201}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-201}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s201
execute @p ~~~ execute @s[scores={spawn=202}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s202
execute @p ~~~ execute @s[scores={spawn=-202}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-202}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s202
execute @p ~~~ execute @s[scores={spawn=203}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s203
execute @p ~~~ execute @s[scores={spawn=-203}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-203}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s203
execute @p ~~~ execute @s[scores={spawn=204}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s204
execute @p ~~~ execute @s[scores={spawn=-204}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-204}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s204
execute @p ~~~ execute @s[scores={spawn=205}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s205
execute @p ~~~ execute @s[scores={spawn=-205}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-205}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s205
execute @p ~~~ execute @s[scores={spawn=206}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s206
execute @p ~~~ execute @s[scores={spawn=-206}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-206}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s206
execute @p ~~~ execute @s[scores={spawn=207}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s207
execute @p ~~~ execute @s[scores={spawn=-207}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-207}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s207
execute @p ~~~ execute @s[scores={spawn=208}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s208
execute @p ~~~ execute @s[scores={spawn=-208}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-208}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s208
execute @p ~~~ execute @s[scores={spawn=209}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s209
execute @p ~~~ execute @s[scores={spawn=-209}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-209}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s209
execute @p ~~~ execute @s[scores={spawn=210}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s210
execute @p ~~~ execute @s[scores={spawn=-210}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-210}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s210
execute @p ~~~ execute @s[scores={spawn=211}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s211
execute @p ~~~ execute @s[scores={spawn=-211}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-211}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s211
execute @p ~~~ execute @s[scores={spawn=212}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s212
execute @p ~~~ execute @s[scores={spawn=-212}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-212}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s212
execute @p ~~~ execute @s[scores={spawn=213}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s213
execute @p ~~~ execute @s[scores={spawn=-213}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-213}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s213
execute @p ~~~ execute @s[scores={spawn=214}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s214
execute @p ~~~ execute @s[scores={spawn=-214}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-214}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s214
execute @p ~~~ execute @s[scores={spawn=215}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s215
execute @p ~~~ execute @s[scores={spawn=-215}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-215}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s215
execute @p ~~~ execute @s[scores={spawn=216}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s216
execute @p ~~~ execute @s[scores={spawn=-216}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-216}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s216
execute @p ~~~ execute @s[scores={spawn=217}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s217
execute @p ~~~ execute @s[scores={spawn=-217}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-217}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s217
execute @p ~~~ execute @s[scores={spawn=218}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s218
execute @p ~~~ execute @s[scores={spawn=-218}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-218}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s218
execute @p ~~~ execute @s[scores={spawn=219}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s219
execute @p ~~~ execute @s[scores={spawn=-219}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-219}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s219
execute @p ~~~ execute @s[scores={spawn=220}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s220
execute @p ~~~ execute @s[scores={spawn=-220}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-220}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s220
execute @p ~~~ execute @s[scores={spawn=221}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s221
execute @p ~~~ execute @s[scores={spawn=-221}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-221}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s221
execute @p ~~~ execute @s[scores={spawn=222}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s222
execute @p ~~~ execute @s[scores={spawn=-222}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-222}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s222
execute @p ~~~ execute @s[scores={spawn=223}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s223
execute @p ~~~ execute @s[scores={spawn=-223}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-223}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s223
execute @p ~~~ execute @s[scores={spawn=224}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s224
execute @p ~~~ execute @s[scores={spawn=-224}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-224}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s224
execute @p ~~~ execute @s[scores={spawn=225}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s225
execute @p ~~~ execute @s[scores={spawn=-225}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-225}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s225
execute @p ~~~ execute @s[scores={spawn=226}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s226
execute @p ~~~ execute @s[scores={spawn=-226}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-226}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s226
execute @p ~~~ execute @s[scores={spawn=227}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s227
execute @p ~~~ execute @s[scores={spawn=-227}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-227}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s227
execute @p ~~~ execute @s[scores={spawn=228}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s228
execute @p ~~~ execute @s[scores={spawn=-228}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-228}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s228
execute @p ~~~ execute @s[scores={spawn=229}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s229
execute @p ~~~ execute @s[scores={spawn=-229}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-229}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s229
execute @p ~~~ execute @s[scores={spawn=230}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s230
execute @p ~~~ execute @s[scores={spawn=-230}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-230}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s230
execute @p ~~~ execute @s[scores={spawn=231}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s231
execute @p ~~~ execute @s[scores={spawn=-231}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-231}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s231
execute @p ~~~ execute @s[scores={spawn=232}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s232
execute @p ~~~ execute @s[scores={spawn=-232}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-232}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s232
execute @p ~~~ execute @s[scores={spawn=233}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s233
execute @p ~~~ execute @s[scores={spawn=-233}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-233}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s233
execute @p ~~~ execute @s[scores={spawn=234}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s234
execute @p ~~~ execute @s[scores={spawn=-234}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-234}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s234
execute @p ~~~ execute @s[scores={spawn=235}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s235
execute @p ~~~ execute @s[scores={spawn=-235}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-235}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s235
execute @p ~~~ execute @s[scores={spawn=236}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s236
execute @p ~~~ execute @s[scores={spawn=-236}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-236}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s236
execute @p ~~~ execute @s[scores={spawn=237}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s237
execute @p ~~~ execute @s[scores={spawn=-237}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-237}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s237
execute @p ~~~ execute @s[scores={spawn=238}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s238
execute @p ~~~ execute @s[scores={spawn=-238}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-238}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s238
execute @p ~~~ execute @s[scores={spawn=239}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s239
execute @p ~~~ execute @s[scores={spawn=-239}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-239}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s239
execute @p ~~~ execute @s[scores={spawn=240}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s240
execute @p ~~~ execute @s[scores={spawn=-240}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-240}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s240
execute @p ~~~ execute @s[scores={spawn=241}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s241
execute @p ~~~ execute @s[scores={spawn=-241}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-241}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s241
execute @p ~~~ execute @s[scores={spawn=242}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s242
execute @p ~~~ execute @s[scores={spawn=-242}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-242}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s242
execute @p ~~~ execute @s[scores={spawn=243}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s243
execute @p ~~~ execute @s[scores={spawn=-243}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-243}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s243
execute @p ~~~ execute @s[scores={spawn=244}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s244
execute @p ~~~ execute @s[scores={spawn=-244}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-244}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s244
execute @p ~~~ execute @s[scores={spawn=245}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s245
execute @p ~~~ execute @s[scores={spawn=-245}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-245}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s245
execute @p ~~~ execute @s[scores={spawn=246}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s246
execute @p ~~~ execute @s[scores={spawn=-246}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-246}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s246
execute @p ~~~ execute @s[scores={spawn=247}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s247
execute @p ~~~ execute @s[scores={spawn=-247}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-247}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s247
execute @p ~~~ execute @s[scores={spawn=248}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s248
execute @p ~~~ execute @s[scores={spawn=-248}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-248}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s248
execute @p ~~~ execute @s[scores={spawn=249}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s249
execute @p ~~~ execute @s[scores={spawn=-249}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-249}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s249
execute @p ~~~ execute @s[scores={spawn=250}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s250
execute @p ~~~ execute @s[scores={spawn=-250}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-250}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s250
execute @p ~~~ execute @s[scores={spawn=251}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s251
execute @p ~~~ execute @s[scores={spawn=-251}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-251}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s251
execute @p ~~~ execute @s[scores={spawn=252}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s252
execute @p ~~~ execute @s[scores={spawn=-252}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-252}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s252
execute @p ~~~ execute @s[scores={spawn=253}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s253
execute @p ~~~ execute @s[scores={spawn=-253}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-253}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s253
execute @p ~~~ execute @s[scores={spawn=254}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s254
execute @p ~~~ execute @s[scores={spawn=-254}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-254}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s254
execute @p ~~~ execute @s[scores={spawn=255}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s255
execute @p ~~~ execute @s[scores={spawn=-255}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-255}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s255
execute @p ~~~ execute @s[scores={spawn=256}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s256
execute @p ~~~ execute @s[scores={spawn=-256}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-256}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s256
execute @p ~~~ execute @s[scores={spawn=257}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s257
execute @p ~~~ execute @s[scores={spawn=-257}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-257}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s257
execute @p ~~~ execute @s[scores={spawn=258}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s258
execute @p ~~~ execute @s[scores={spawn=-258}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-258}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s258
execute @p ~~~ execute @s[scores={spawn=259}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s259
execute @p ~~~ execute @s[scores={spawn=-259}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-259}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s259
execute @p ~~~ execute @s[scores={spawn=260}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s260
execute @p ~~~ execute @s[scores={spawn=-260}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-260}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s260
execute @p ~~~ execute @s[scores={spawn=261}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s261
execute @p ~~~ execute @s[scores={spawn=-261}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-261}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s261
execute @p ~~~ execute @s[scores={spawn=262}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s262
execute @p ~~~ execute @s[scores={spawn=-262}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-262}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s262
execute @p ~~~ execute @s[scores={spawn=263}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s263
execute @p ~~~ execute @s[scores={spawn=-263}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-263}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s263
execute @p ~~~ execute @s[scores={spawn=264}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s264
execute @p ~~~ execute @s[scores={spawn=-264}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-264}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s264
execute @p ~~~ execute @s[scores={spawn=265}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s265
execute @p ~~~ execute @s[scores={spawn=-265}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-265}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s265
execute @p ~~~ execute @s[scores={spawn=266}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s266
execute @p ~~~ execute @s[scores={spawn=-266}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-266}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s266
execute @p ~~~ execute @s[scores={spawn=267}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s267
execute @p ~~~ execute @s[scores={spawn=-267}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-267}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s267
execute @p ~~~ execute @s[scores={spawn=268}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s268
execute @p ~~~ execute @s[scores={spawn=-268}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-268}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s268
execute @p ~~~ execute @s[scores={spawn=269}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s269
execute @p ~~~ execute @s[scores={spawn=-269}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-269}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s269
execute @p ~~~ execute @s[scores={spawn=270}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s270
execute @p ~~~ execute @s[scores={spawn=-270}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-270}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s270
execute @p ~~~ execute @s[scores={spawn=271}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s271
execute @p ~~~ execute @s[scores={spawn=-271}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-271}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s271
execute @p ~~~ execute @s[scores={spawn=272}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s272
execute @p ~~~ execute @s[scores={spawn=-272}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-272}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s272
execute @p ~~~ execute @s[scores={spawn=273}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s273
execute @p ~~~ execute @s[scores={spawn=-273}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-273}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s273
execute @p ~~~ execute @s[scores={spawn=274}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s274
execute @p ~~~ execute @s[scores={spawn=-274}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-274}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s274
execute @p ~~~ execute @s[scores={spawn=275}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s275
execute @p ~~~ execute @s[scores={spawn=-275}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-275}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s275
execute @p ~~~ execute @s[scores={spawn=276}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s276
execute @p ~~~ execute @s[scores={spawn=-276}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-276}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s276
execute @p ~~~ execute @s[scores={spawn=277}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s277
execute @p ~~~ execute @s[scores={spawn=-277}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-277}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s277
execute @p ~~~ execute @s[scores={spawn=278}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s278
execute @p ~~~ execute @s[scores={spawn=-278}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-278}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s278
execute @p ~~~ execute @s[scores={spawn=279}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s279
execute @p ~~~ execute @s[scores={spawn=-279}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-279}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s279
execute @p ~~~ execute @s[scores={spawn=280}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s280
execute @p ~~~ execute @s[scores={spawn=-280}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-280}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s280
execute @p ~~~ execute @s[scores={spawn=281}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s281
execute @p ~~~ execute @s[scores={spawn=-281}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-281}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s281
execute @p ~~~ execute @s[scores={spawn=282}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s282
execute @p ~~~ execute @s[scores={spawn=-282}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-282}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s282
execute @p ~~~ execute @s[scores={spawn=283}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s283
execute @p ~~~ execute @s[scores={spawn=-283}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-283}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s283
execute @p ~~~ execute @s[scores={spawn=284}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s284
execute @p ~~~ execute @s[scores={spawn=-284}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-284}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s284
execute @p ~~~ execute @s[scores={spawn=285}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s285
execute @p ~~~ execute @s[scores={spawn=-285}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-285}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s285
execute @p ~~~ execute @s[scores={spawn=286}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s286
execute @p ~~~ execute @s[scores={spawn=-286}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-286}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s286
execute @p ~~~ execute @s[scores={spawn=287}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s287
execute @p ~~~ execute @s[scores={spawn=-287}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-287}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s287
execute @p ~~~ execute @s[scores={spawn=288}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s288
execute @p ~~~ execute @s[scores={spawn=-288}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-288}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s288
execute @p ~~~ execute @s[scores={spawn=289}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s289
execute @p ~~~ execute @s[scores={spawn=-289}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-289}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s289
execute @p ~~~ execute @s[scores={spawn=290}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s290
execute @p ~~~ execute @s[scores={spawn=-290}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-290}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s290
execute @p ~~~ execute @s[scores={spawn=291}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s291
execute @p ~~~ execute @s[scores={spawn=-291}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-291}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s291
execute @p ~~~ execute @s[scores={spawn=292}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s292
execute @p ~~~ execute @s[scores={spawn=-292}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-292}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s292
execute @p ~~~ execute @s[scores={spawn=293}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s293
execute @p ~~~ execute @s[scores={spawn=-293}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-293}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s293
execute @p ~~~ execute @s[scores={spawn=294}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s294
execute @p ~~~ execute @s[scores={spawn=-294}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-294}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s294
execute @p ~~~ execute @s[scores={spawn=295}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s295
execute @p ~~~ execute @s[scores={spawn=-295}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-295}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s295
execute @p ~~~ execute @s[scores={spawn=296}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s296
execute @p ~~~ execute @s[scores={spawn=-296}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-296}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s296
execute @p ~~~ execute @s[scores={spawn=297}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s297
execute @p ~~~ execute @s[scores={spawn=-297}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-297}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s297
execute @p ~~~ execute @s[scores={spawn=298}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s298
execute @p ~~~ execute @s[scores={spawn=-298}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-298}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s298
execute @p ~~~ execute @s[scores={spawn=299}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s299
execute @p ~~~ execute @s[scores={spawn=-299}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-299}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s299
execute @p ~~~ execute @s[scores={spawn=384}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s384
execute @p ~~~ execute @s[scores={spawn=-384}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-384}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s384
execute @p ~~~ execute @s[scores={spawn=447}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s447
execute @p ~~~ execute @s[scores={spawn=-447}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-447}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s447
execute @p ~~~ execute @s[scores={spawn=448}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s448
execute @p ~~~ execute @s[scores={spawn=-448}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-448}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s448
execute @p ~~~ execute @s[scores={spawn=493}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s493
execute @p ~~~ execute @s[scores={spawn=-493}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-493}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s493
execute @p ~~~ execute @s[scores={spawn=658}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s658
execute @p ~~~ execute @s[scores={spawn=-658}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-658}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s658
execute @p ~~~ execute @s[scores={spawn=700}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s700
execute @p ~~~ execute @s[scores={spawn=-700}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-700}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s700
execute @p ~~~ execute @s[scores={spawn=720}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s720
execute @p ~~~ execute @s[scores={spawn=-720}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-720}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s720


execute @p ~~~ execute @s[scores={spawn=000}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s000
execute @p ~~~ execute @s[scores={spawn=-000}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] serp:shiny
execute @p ~~~ execute @s[scores={spawn=-000}] ~~~ event entity @e[type=serp:spawn,r=3,c=1] s000


scoreboard players set @p spawn 0
